### ISSUE TITLE
Ansible Permission Issues Inside the pgo-deploy Pod

### ISSUE THREAD

**Issue by pasmod** [CrunchyData/postgres-operator#1507]
**Description of the Problem**
I would like to run the PostgreSQL Operator on my Kubernetes cluster (bare metal), based on the tutorial in [Quickstart](https://access.crunchydata.com/documentation/postgres-operator/4.3.0/quickstart/). The storage class that I use is **rook-ceph-block**. After creating the **pgo** namespace and applying the YAML file for the operator, a **pgo-deploy** pod is started, but has the status **Terminated: Error**. There seems that Ansible inside the container has permission problems writing to **DEFAULT_LOCAL_TMP**.

**To Reproduce**

**Step 1**
`kubectl create namespace pgo`

**Step 2**

`curl https://raw.githubusercontent.com/CrunchyData/postgres-operator/v4.3.0/installers/kubectl/postgres-operator.yml > postgres-operator.yml`

**Step 3**
Configuration
                  
```
- name: BACKREST_STORAGE
   value: "rook-ceph-block"
- name: BACKUP_STORAGE
   value: "rook-ceph-block"
- name: PRIMARY_STORAGE
   value: "rook-ceph-block"
- name: REPLICA_STORAGE
   value: "rook-ceph-block"
```

**Step 4**
`kubectl apply -f postgres-operator.yml`

**Extra Information**

```
kubectl logs -f -n pgo pgo-deploy-wkl8c

Unhandled error:
 Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 559, in update_config_data
    value, origin = self.get_config_value_and_origin(config, configfile)
  File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 503, in get_config_value_and_origin
    value = ensure_type(value, defs[config].get('type'), origin=origin)
  File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 122, in ensure_type
    makedirs_safe(value, 0o700)
  File "/usr/lib/python2.7/site-packages/ansible/utils/path.py", line 90, in makedirs_safe
    raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e)))
AnsibleError: Unable to create local directories(/usr/sbin/.ansible/tmp): [Errno 13] Permission denied: '/usr/sbin/.ansible'


Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 62, in <module>
    import ansible.constants as C
  File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 174, in <module>
    config = ConfigManager()
  File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 291, in __init__
    self.update_config_data()
  File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 571, in update_config_data
    raise AnsibleError("Invalid settings supplied for %s: %s\n" % (config, to_native(e)), orig_exc=e)
ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: Unable to create local directories(/usr/sbin/.ansible/tmp): [Errno 13] Permission denied: '/usr/sbin/.ansible'
```
---------------------------

```
kubectl describe pod -n pgo pgo-deploy-wkl8c

Name:         pgo-deploy-wkl8c
Namespace:    pgo
Priority:     0
Node:         node5/82.141.39.101
Start Time:   Tue, 12 May 2020 09:42:48 +0200
Labels:       controller-uid=1b5f46fc-be31-4d80-8619-0c2f5b80e052
              job-name=pgo-deploy
Annotations:  <none>
Status:       Failed
IP:           10.233.115.97
IPs:
  IP:           10.233.115.97
Controlled By:  Job/pgo-deploy
Containers:
  pgo-deploy:
    Container ID:  docker://6612ec147d64589faea7dc569ca955a8600d4b34a92250c79e81f1df2258cde2
    Image:         registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.0
    Image ID:      docker-pullable://registry.developers.crunchydata.com/crunchydata/pgo-deployer@sha256:36b81e8dcfc246c4328ea2a0f75136cd1c9bef7e64e142048c92b03d0e088b1e
    Port:          <none>
    Host Port:     <none>
    Command:
      /pgo-deploy.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 12 May 2020 09:42:50 +0200
      Finished:     Tue, 12 May 2020 09:42:51 +0200
    Ready:          False
    Restart Count:  0
    Environment:
      ARCHIVE_MODE:                  true
      ARCHIVE_TIMEOUT:               60
      BACKREST:                      true
      BADGER:                        false
      CRUNCHY_DEBUG:                 false
      CREATE_RBAC:                   true
      CCP_IMAGE_PREFIX:              registry.developers.crunchydata.com/crunchydata
      CCP_IMAGE_TAG:                 centos7-12.2-4.3.0
      DB_PASSWORD_LENGTH:            24
      DB_PORT:                       5432
      DB_REPLICAS:                   0
      DB_USER:                       testuser
      DEFAULT_INSTANCE_MEMORY:       128Mi
      DEFAULT_PGBACKREST_MEMORY:
      DEFAULT_PGBOUNCER_MEMORY:
      DEPLOY_ACTION:                 install
      DISABLE_AUTO_FAILOVER:         false
      EXPORTERPORT:                  9187
      METRICS:                       false
      NAMESPACE:                     pgo
      NAMESPACE_MODE:                dynamic
      PGBADGERPORT:                  10000
      PGO_ADMIN_PASSWORD:            b4t@WBnZ66
      PGO_ADMIN_PERMS:               *
      PGO_ADMIN_ROLE_NAME:           pgoadmin
      PGO_ADMIN_USERNAME:            admin
      PGO_CLIENT_VERSION:            v4.3.0
      PGO_IMAGE_PREFIX:              registry.developers.crunchydata.com/crunchydata
      PGO_IMAGE_TAG:                 centos7-4.3.0
      PGO_INSTALLATION_NAME:         devtest
      PGO_OPERATOR_NAMESPACE:        pgo
      SCHEDULER_TIMEOUT:             3600
      BACKREST_STORAGE:              rook-ceph-block
      BACKUP_STORAGE:                rook-ceph-block
      PRIMARY_STORAGE:               rook-ceph-block
      REPLICA_STORAGE:               rook-ceph-block
      WAL_STORAGE:
      STORAGE1_NAME:                 hostpathstorage
      STORAGE1_ACCESS_MODE:          ReadWriteMany
      STORAGE1_SIZE:                 1G
      STORAGE1_TYPE:                 create
      STORAGE2_NAME:                 replicastorage
      STORAGE2_ACCESS_MODE:          ReadWriteMany
      STORAGE2_SIZE:                 700M
      STORAGE2_TYPE:                 create
      STORAGE3_NAME:                 nfsstorage
      STORAGE3_ACCESS_MODE:          ReadWriteMany
      STORAGE3_SIZE:                 1G
      STORAGE3_TYPE:                 create
      STORAGE3_SUPPLEMENTAL_GROUPS:  65534
      STORAGE4_NAME:                 nfsstoragered
      STORAGE4_ACCESS_MODE:          ReadWriteMany
      STORAGE4_SIZE:                 1G
      STORAGE4_MATCH_LABEL:          crunchyzone=red
      STORAGE4_TYPE:                 create
      STORAGE4_SUPPLEMENTAL_GROUPS:  65534
      STORAGE5_NAME:                 storageos
      STORAGE5_ACCESS_MODE:          ReadWriteOnce
      STORAGE5_SIZE:                 5Gi
      STORAGE5_TYPE:                 dynamic
      STORAGE5_CLASS:                fast
      STORAGE6_NAME:                 primarysite
      STORAGE6_ACCESS_MODE:          ReadWriteOnce
      STORAGE6_SIZE:                 4G
      STORAGE6_TYPE:                 dynamic
      STORAGE6_CLASS:                primarysite
      STORAGE7_NAME:                 alternatesite
      STORAGE7_ACCESS_MODE:          ReadWriteOnce
      STORAGE7_SIZE:                 4G
      STORAGE7_TYPE:                 dynamic
      STORAGE7_CLASS:                alternatesite
      STORAGE8_NAME:                 gce
      STORAGE8_ACCESS:               ReadWriteOnce
      STORAGE8_SIZE:                 300M
      STORAGE8_TYPE:                 dynamic
      STORAGE8_CLASS:                standard
      STORAGE9_NAME:                 rook
      STORAGE9_ACCESS_MODE:          ReadWriteOnce
      STORAGE9_SIZE:                 1Gi
      STORAGE9_TYPE:                 dynamic
      STORAGE9_CLASS:                rook-ceph-block
      DEFAULT_LOCAL_TMP:             /tmp
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-deployer-sa-token-xp7vg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  pgo-deployer-sa-token-xp7vg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-deployer-sa-token-xp7vg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From               Message
  ----    ------     ----       ----               -------
  Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned pgo/pgo-deploy-wkl8c to node5
  Normal  Pulled     13m        kubelet, node5     Container image "registry.developers.crunchydata.com/crunchydata/pgo-deployer:centos7-4.3.0" already present on machine
  Normal  Created    13m        kubelet, node5     Created container pgo-deploy
  Normal  Started    13m        kubelet, node5     Started container pgo-deploy
```

**Comment by jkatz** [comment]
Are the below variables present? This was a known issue with the file in master (addressed in #1496):

```yaml
- name: ANSIBLE_CONFIG
value: "/ansible/ansible.cfg"
- name: HOME
value: "/tmp"
```

I do not see these variables in your describe.
