### ISSUE TITLE
Data lost after primary to secondary fail over due to disk space issue

### ISSUE THREAD

**Issue by shaikmuzakkir** [CrunchyData/postgres-operator#1723]
** Which example are you working with? **
postgres-operator
**What is the current behavior?**
Data is lost after primary to secondary fail over due to disk space issue. 

Primary logs:
`2020-07-14 23:50:13,572 ERROR: unable to create backup copies of configuration files
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/config.py", line 393, in save_configuration_files
    shutil.copy(config_file, backup_file)
  File "/usr/lib64/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib64/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device`

We have a monitoring setup with prometheus-postgres-exporter helm chart which showed 10 Billion rows in the insert data but after failover the graph shows only 1.15 Billion which indicates there is a data loss.

**What is the expected behavior?**

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**
psql deployed on kubernetes with crunchydata setup.

If possible please run the following on the kubernetes or OpenShift (oc) commands and provide the result:
 Below node was primary which failed over.
```
[root@node /]# k describe pod mycluster-jaai-6c5cc57f5c-7t99l -n pgo
Name:               mycluster-jaai-6c5cc57f5c-7t99l
Namespace:          pgo
Priority:           0
PriorityClassName:  <none>
Node:               node02-02/10.232.219.206
Start Time:         Thu, 25 Jun 2020 14:19:41 +0000
Labels:             crunchy-pgha-scope=mycluster
                    crunchy_collect=false
                    deployment-name=mycluster-jaai
                    name=mycluster-replica
                    pg-cluster=mycluster
                    pg-pod-anti-affinity=
                    pgo-pg-database=true
                    pgo-version=4.3.2
                    pod-template-hash=6c5cc57f5c
                    replica-name=mycluster-jaai
                    role=replica
                    service-name=mycluster-replica
                    vendor=crunchydata
                    workflowid=f4013cd5-be06-4cf8-a6f1-1107ac7c7af8
Annotations:        cni.projectcalico.org/podIP: 192.168.5.159/32
                    status:
                      {"conn_url":"postgres://192.168.5.159:5432/postgres","api_url":"http://192.168.5.159:8009/patroni","state":"running","role":"replica","ver...
Status:             Running
IP:                 192.168.5.159
Controlled By:      ReplicaSet/mycluster-jaai-6c5cc57f5c
Containers:
  database:
    Container ID:   docker://20fa686d616f9bf9b29fda70c68b634f4ad680a147d0881c93a51573fddefd33
    Image:          hub.docker.prod.walmart.com/crunchydata/crunchy-postgres-ha:centos7-12.3-4.3.2
    Image ID:       docker-pullable://hub.docker.prod.walmart.com/crunchydata/crunchy-postgres-ha@sha256:504ec23b80011ff5ce8586f7ec44e1952ffcaf448153297278274b8d0957bf68
    Ports:          5432/TCP, 8009/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 25 Jun 2020 14:19:42 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      memory:   128Mi
    Liveness:   exec [/opt/cpm/bin/health/pgha-liveness.sh] delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:  exec [/opt/cpm/bin/health/pgha-readiness.sh] delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PGHA_PG_PORT:                       5432
      PGHA_USER:                          postgres
      PATRONI_POSTGRESQL_DATA_DIR:        /pgdata/mycluster-jaai
      PGBACKREST_STANZA:                  db
      PGBACKREST_REPO1_HOST:              mycluster-backrest-shared-repo
      BACKREST_SKIP_CREATE_STANZA:        true
      PGHA_PGBACKREST:                    true
      PGBACKREST_REPO1_PATH:              /backrestrepo/mycluster-backrest-shared-repo
      PGBACKREST_DB_PATH:                 /pgdata/mycluster-jaai
      ENABLE_SSHD:                        true
      PGBACKREST_LOG_PATH:                /tmp
      PGBACKREST_PG1_SOCKET_PATH:         /tmp
      PGBACKREST_PG1_PORT:                5432
      PGBACKREST_REPO_TYPE:               posix
      PGHA_PGBACKREST_LOCAL_S3_STORAGE:   false
      PGHA_DATABASE:                      mycluster
      PGHA_CRUNCHYADM:                    true
      PGHA_REPLICA_REINIT_ON_START_FAIL:  true
      PGHA_SYNC_REPLICATION:              false
      PGHA_TLS_ENABLED:                   false
      PGHA_TLS_ONLY:                      false
      PGHA_STANDBY:                       false
      PATRONI_KUBERNETES_NAMESPACE:       pgo (v1:metadata.namespace)
      PATRONI_KUBERNETES_SCOPE_LABEL:     crunchy-pgha-scope
      PATRONI_SCOPE:                       (v1:metadata.labels['crunchy-pgha-scope'])
      PATRONI_KUBERNETES_LABELS:          {vendor: "crunchydata"}
      PATRONI_LOG_LEVEL:                  INFO
      PGHOST:                             /tmp
    Mounts:
      /backrestrepo from backrestrepo (rw)
      /crunchyadm from crunchyadm (rw)
      /dev/shm from dshm (rw)
      /pgconf from pgconf-volume (rw)
      /pgconf/pgreplicator from primary-volume (rw)
      /pgconf/pgsuper from root-volume (rw)
      /pgconf/pguser from user-volume (rw)
      /pgdata from pgdata (rw)
      /recover from recover-volume (rw)
      /sshd from sshd (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from pgo-pg-token-k4bpz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  pgdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mycluster-jaai
    ReadOnly:   false
  user-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mycluster-testuser-secret
    Optional:    false
  primary-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mycluster-primaryuser-secret
    Optional:    false
  collect-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  sshd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mycluster-backrest-repo-config
    Optional:    false
  root-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mycluster-postgres-secret
    Optional:    false
  recover-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  report:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  backrestrepo:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  crunchyadm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  pgconf-volume:
    Type:               Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:      mycluster-pgha-config
    ConfigMapOptional:  0xc00041cc3d
  pgo-pg-token-k4bpz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgo-pg-token-k4bpz
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                      From                                          Message
  ----     ------            ----                     ----                                          -------
  Warning  DNSConfigForming  2m49s (x21002 over 10d)  kubelet, node02-03  Search Line limits were exceeded, some search paths have been omitted, the applied search line is: pgo.svc.cluster.local svc.cluster.local cluster.local 
```

 kubectl describe pvc

```
[root@node /]# k describe pvc mycluster-jaai -n pgo
Name:          mycluster-jaai
Namespace:     pgo
StorageClass:  local-storage
Status:        Bound
Volume:        mycluster4
Labels:        pg-cluster=mycluster
               pgremove=true
               vendor=crunchydata
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Events:        <none>
Mounted By:    mycluster-jaai-6c5cc57f5c-7t99l
```

I just wanted to understand what is the expected behavious when a node fails over due to disk space issue and why I'm seeing data loss as per the graph.

**Comment by jkatz** [comment]
I'm sorry to hear you are having an issue.
 
It's tough to diagnose the exact issue based on the above information and likely would require a bit more discussion. From the above, it does sound like failover worked correctly. Around potential data loss, I can think of a few things:

- Replication mode. Asynchronous replication is not designed to protect against transaction loss, it's designed to commit the transaction as quickly to the primary as possible, and allow the transaction to be propagated and written to the replicas "in its own time." If you are looking to guard against transaction loss, you would need to use [synchronous replication](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/high-availability/#synchronous-replication-guarding-against-transactions-loss). Note that synchronous replication has its own tradeoffs around availability and performance.

- Monitoring tools: we use our own suite of monitoring tools to diagnose issues based on [pgMonitor](https://github.com/CrunchyData/pgmonitor/), as well as some tools built into `pgo` that can show things like replication lag. I mention this as I'm not sure exactly what your metrics are showing (e.g. inserts over time vs. actually data in database) to strictly say "there is data loss."

We'd be happy to get on a web meeting to discuss in more details. If you are a Crunchy Data customer and this involves production data, please contact Crunchy Customer Support, otherwise, [please reach out here](https://www.crunchydata.com/contact).

**Comment by shaikmuzakkir** [comment]
Thanks for your quick response. Is there a standard way for setting up pgmonitor on a kubernetes cluster? And can you suggest where/how the synchronous replication can configurations can be done?

**Comment by jkatz** [comment]
Both are covered in the [documentation](https://access.crunchydata.com/documentation/postgres-operator/).
