### ISSUE TITLE
Upgrading major versions of pg with no downtime - logical replication set but standby does not work when versions are different major versions

### ISSUE THREAD

**Issue by alrooney** [CrunchyData/postgres-operator#1945]
@jkatz in this issue you discuss an architecture that is basically the standby architecture using s3 with logical replication for syncing: https://github.com/CrunchyData/postgres-operator/issues/1664

I tried this with pg 11.8 running on the primary and bringing up a standby with pg 12.4.  Given that these were using logical replication to sync I would have thought that I could bring up the pg 12.4 db as a standby with the 11.8 db as the primary.  However, in the logs after syncing the 12.4 standby it fails to start the db.  Should this work or should it not?  If not, why not since there is logical replication and that should allow for different versions of the db to talk to each other?

**Comment by alrooney** [comment]
Here are logs from the standby side of the architecture i.e. trying to bring up a 12.4 db from the logical wal of a 11.8 db: 
```
alec@Alecs-MacBook-Pro ~ $ kk logs -f retroelk-staging-7b9c89dfcf-rxgkd -n pgo -c database
Wed Oct  7 20:38:39 UTC 2020 INFO: postgres-ha pre-bootstrap starting...
Wed Oct  7 20:38:39 UTC 2020 INFO: pgBackRest auto-config disabled
Wed Oct  7 20:38:39 UTC 2020 INFO: PGHA_PGBACKREST_LOCAL_S3_STORAGE and PGHA_PGBACKREST_INITIALIZE will be ignored if provided
Wed Oct  7 20:38:39 UTC 2020 INFO: Defaults have been set for the following postgres-ha auto-configuration env vars: PGHA_DEFAULT_CONFIG, PGHA_BASE_BOOTSTRAP_CONFIG, PGHA_BASE_PG_CONFIG
Wed Oct  7 20:38:39 UTC 2020 INFO: Defaults have been set for the following postgres-ha env vars: PGHA_PATRONI_PORT
Wed Oct  7 20:38:39 UTC 2020 INFO: Defaults have been set for the following Patroni env vars: PATRONI_NAME, PATRONI_RESTAPI_LISTEN, PATRONI_RESTAPI_CONNECT_ADDRESS, PATRONI_POSTGRESQL_LISTEN, PATRONI_POSTGRESQL_CONNECT_ADDRESS
Wed Oct  7 20:38:39 UTC 2020 INFO: Setting postgres-ha configuration for database user credentials
Wed Oct  7 20:38:39 UTC 2020 INFO: Setting 'pguser' credentials using file system
Wed Oct  7 20:38:39 UTC 2020 INFO: Setting 'superuser' credentials using file system
Wed Oct  7 20:38:39 UTC 2020 INFO: Setting 'replicator' credentials using file system
ls: cannot access '/pgdata/retroelk-staging': No such file or directory
Wed Oct  7 20:38:39 UTC 2020 INFO: Applying base bootstrap config to postgres-ha configuration
Wed Oct  7 20:38:39 UTC 2020 INFO: Applying base postgres config to postgres-ha configuration
Wed Oct  7 20:38:39 UTC 2020 INFO: Applying pgbackrest config to postgres-ha configuration
Wed Oct  7 20:38:39 UTC 2020 INFO: PGDATA directory is empty on node identifed as Primary
Wed Oct  7 20:38:39 UTC 2020 INFO: initdb configuration will be applied to intitilize a new database
Wed Oct  7 20:38:39 UTC 2020 INFO: Applying configuration to bootstrap a standby cluster
Wed Oct  7 20:38:39 UTC 2020 INFO: Applying standard (non-TLS) remote connection configuration to pg_hba.conf
Wed Oct  7 20:38:39 UTC 2020 INFO: Custom postgres-ha configuration file not detected
Wed Oct  7 20:38:39 UTC 2020 INFO: Finished building postgres-ha configuration file '/tmp/postgres-ha-bootstrap.yaml'
Wed Oct  7 20:38:39 UTC 2020 INFO: postgres-ha pre-bootstrap complete!  The following configuration will be utilized to initialize 
******************************
postgres-ha (PGHA) env vars:
******************************
PGHA_BASE_PG_CONFIG=true
PGHA_PATRONI_PORT=8009
PGHA_PG_PORT=5432
PGHA_CRUNCHYADM=true
PGHA_PGBACKREST_LOCAL_S3_STORAGE=true
PGHA_SYNC_REPLICATION=false
PGHA_USER=postgres
PGHA_INIT=true
PGHA_DEFAULT_CONFIG=true
PGHA_REPLICA_REINIT_ON_START_FAIL=true
PGHA_PGBACKREST=true
PGHA_BASE_BOOTSTRAP_CONFIG=true
PGHA_PGBACKREST_S3_VERIFY_TLS=true
PGHA_STANDBY=true
PGHA_TLS_ONLY=false
PGHA_TLS_ENABLED=false
PGHA_DATABASE=retroelk-staging
******************************
Patroni env vars:
******************************
PATRONI_POSTGRESQL_CONNECT_ADDRESS=10.244.0.28:5432
PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
PATRONI_NAME=retroelk-staging-7b9c89dfcf-rxgkd
PATRONI_SCOPE=retroelk-staging
PATRONI_RESTAPI_LISTEN=0.0.0.0:8009
PATRONI_POSTGRESQL_DATA_DIR=/pgdata/retroelk-staging
PATRONI_RESTAPI_CONNECT_ADDRESS=10.244.0.28:8009
PATRONI_LOG_LEVEL=INFO
PATRONI_KUBERNETES_LABELS={vendor: "crunchydata"}
PATRONI_KUBERNETES_SCOPE_LABEL=crunchy-pgha-scope
PATRONI_KUBERNETES_NAMESPACE=pgo
******************************
Patroni bootstrap method: initdb
******************************
Patroni configuration file:
******************************
bootstrap:
  method: initdb
  pgbackrest_init:
    command: '/opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh primary'
    keep_existing_recovery_conf: true
  existing_init:
    command: '/opt/cpm/bin/bootstrap/create-from-existing.sh'
    keep_existing_recovery_conf: true
  dcs:
    postgresql:
      parameters:
        unix_socket_directories: /tmp,/crunchyadm
        wal_level: logical
        archive_mode: on
        archive_command: "source /opt/cpm/bin/pgbackrest/pgbackrest-archive-push-local-s3.sh
          %p"
        archive_timeout: 60
        log_directory: pg_log
        shared_buffers: 128MB
        temp_buffers: 8MB
        log_min_duration_statement: 60000
        log_statement: none
        work_mem: 4MB
        max_wal_senders: 6
        shared_preload_libraries: pgaudit.so,pg_stat_statements.so,pgnodemx.so
      use_slots: false
      recovery_conf:
        restore_command: 'source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh &&
          pgbackrest archive-get %f "%p"'
      use_pg_rewind: true
    standby_cluster:
      create_replica_methods:
      - pgbackrest_standby
      restore_command: 'source /opt/cpm/bin/pgbackrest/pgbackrest-set-env.sh && pgbackrest
        archive-get %f "%p"'
  post_bootstrap: /opt/cpm/bin/bootstrap/post-bootstrap.sh
  initdb:
  - encoding: UTF8
  - data-checksums
postgresql:
  use_unix_socket: true
  pgpass: /tmp/.pgpass
  create_replica_methods:
  - pgbackrest
  - basebackup
  pgbackrest:
    command: '/opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh replica'
    keep_data: true
    no_params: true
  pgbackrest_standby:
    command: '/opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh standby'
    keep_data: true
    no_params: true
    no_master: 1
  remove_data_directory_on_rewind_failure: true
  callbacks:
    on_role_change: /opt/cpm/bin/callbacks/pgha-on-role-change.sh
  pg_hba:
  - local all postgres peer
  - local all crunchyadm peer
  - host replication primaryuser 0.0.0.0/0 md5
  - host all primaryuser 0.0.0.0/0 reject
  - host all all 0.0.0.0/0 md5
Wed Oct  7 20:38:39 UTC 2020 INFO: Applying SSHD..
Wed Oct  7 20:38:39 UTC 2020 INFO: Checking for SSH Host Keys in /sshd..
Wed Oct  7 20:38:39 UTC 2020 INFO: Checking for authorized_keys in /sshd
Wed Oct  7 20:38:39 UTC 2020 INFO: Checking for sshd_config in /sshd
Wed Oct  7 20:38:39 UTC 2020 INFO: setting up .ssh directory
Wed Oct  7 20:38:39 UTC 2020 INFO: Starting SSHD..
Wed Oct  7 20:38:39 UTC 2020 INFO: Starting background process to monitor Patroni initization and restart the database if needed
Wed Oct  7 20:38:39 UTC 2020 INFO: Initializing cluster bootstrap with command: '/usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml'
Wed Oct  7 20:38:39 UTC 2020 INFO: Running Patroni as PID 1
2020-10-07 20:38:40,130 INFO: No PostgreSQL configuration items changed, nothing to reload.
2020-10-07 20:38:40,137 INFO: Lock owner: None; I am retroelk-staging-7b9c89dfcf-rxgkd
2020-10-07 20:38:40,170 INFO: trying to bootstrap a new standby leader
Wed Oct  7 20:38:40 UTC 2020 INFO: Empty PGDATA dir found for standby, a non-delta restore will be peformed
2020-10-07 20:38:50,635 INFO: Lock owner: None; I am retroelk-staging-7b9c89dfcf-rxgkd
2020-10-07 20:38:50,636 INFO: not healthy enough for leader race
2020-10-07 20:44:50,635 INFO: not healthy enough for leader race
2020-10-07 20:44:50,635 INFO: bootstrap_standby_leader in progress
Wed Oct  7 20:44:59 UTC 2020 INFO: standby pgBackRest restore complete
2020-10-07 20:44:59,007 INFO: replica has been created using pgbackrest_standby
2020-10-07 20:44:59,013 INFO: bootstrapped clone from remote master None
2020-10-07 20:44:59.260 UTC [2999] FATAL:  database files are incompatible with server
2020-10-07 20:44:59.260 UTC [2999] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.4.
2020-10-07 20:44:59,272 INFO: postmaster pid=2999
/tmp:5432 - no response
2020-10-07 20:44:59,294 INFO: removing initialize key after failed attempt to bootstrap the cluster
2020-10-07 20:44:59,302 INFO: renaming data directory to /pgdata/retroelk-staging_2020-10-07-20-44-59
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1427, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1330, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1226, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1219, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

**Comment by jkatz** [comment]
How did you initialize the 12.4 cluster? It appears it's still using a PG 11 data directory:

```
2020-10-07 20:44:59.260 UTC [2999] FATAL:  database files are incompatible with server
2020-10-07 20:44:59.260 UTC [2999] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.4.
```

If you restored that cluster from an existing pgBackRest backup, you would first need to run `pg_upgrade` on it. After that, you can work on synchronizing the data via logical replication, though there is a lot to consider if you are going about it this way,  in particular, the point-in-time that the logical replication begins.

Likely, you would want to bring up an empty PostgreSQL 12 database and then logically replicate the PG 11 data into that. There are some blogs et al. floating around on how to do that -- they may not be Operator specific, but they would cover the general idea.

**Comment by alrooney** [comment]
I brought up an empty pg 12 cluster as a standby of a pg 11 cluster.  I guess backrest doesn't support that which is the issue.  Will look into some of the blogs on using logical replication.

**Comment by alrooney** [comment]
Question: Now trying to bring up a pgo 4.5.0 pg 11.9 cluster as a standby of a pgo 4.3.2 pg 11.8 cluster.  Should that work?

**Comment by alrooney** [comment]
Getting this error to trying that out: 
```
2020-10-07 23:34:52,846 INFO: not healthy enough for leader race
2020-10-07 23:34:52,847 INFO: bootstrap_standby_leader in progress
Wed Oct  7 23:35:00 UTC 2020 INFO: standby pgBackRest restore complete
2020-10-07 23:35:00,784 INFO: replica has been created using pgbackrest_standby
2020-10-07 23:35:00,790 INFO: bootstrapped clone from remote master None
2020-10-07 23:35:01.070 UTC [2861] LOG:  pgaudit extension initialized
2020-10-07 23:35:01.072 UTC [2861] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-10-07 23:35:01,080 INFO: postmaster pid=2861
2020-10-07 23:35:01.085 UTC [2861] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-07 23:35:01.100 UTC [2861] LOG:  listening on Unix socket "/crunchyadm/.s.PGSQL.5432"
2020-10-07 23:35:01.253 UTC [2861] LOG:  redirecting log output to logging collector process
2020-10-07 23:35:01.253 UTC [2861] HINT:  Future log output will appear in directory "pg_log".
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
2020-10-07 23:35:02,847 INFO: Lock owner: None; I am retroelk-staging-798bf54db7-n8mf2
2020-10-07 23:35:02,847 INFO: not healthy enough for leader race
2020-10-07 23:35:02,870 INFO: bootstrap_standby_leader in progress
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
2020-10-07 23:35:08,676 WARNING: Retry got exception: 'connection problems'
/tmp:5432 - rejecting connections
/tmp:5432 - accepting connections
2020-10-07 23:35:10,409 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2020-10-07 23:35:10,415 INFO: Reaped pid=3039, exit status=0
2020-10-07 23:35:10,467 INFO: establishing a new patroni connection to the postgres cluster
2020-10-07 23:35:10,569 INFO: initialized a new cluster
Wed Oct  7 23:35:10 UTC 2020 INFO: PGHA_INIT is 'true', waiting to initialize as primary
2020-10-07 23:35:20,909 INFO: Lock owner: retroelk-staging-798bf54db7-n8mf2; I am retroelk-staging-798bf54db7-n8mf2
2020-10-07 23:35:20,941 INFO: no action.  i am the standby leader with the lock
2020-10-07 23:35:30,909 INFO: Lock owner: retroelk-staging-798bf54db7-n8mf2; I am retroelk-staging-798bf54db7-n8mf2
2020-10-07 23:35:30,982 INFO: no action.  i am the standby leader with the lock
2020-10-07 23:35:40,910 INFO: Lock owner: retroelk-staging-798bf54db7-n8mf2; I am retroelk-staging-798bf54db7-n8mf2
2020-10-07 23:35:40,982 INFO: no action.  i am the standby leader with the lock
2020-10-07 23:35:47,246 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 546, in query
    cursor.execute(sql, params)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 484, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 466, in query
    return self.server.query(sql, *params)
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 551, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: 'connection problems'
2020-10-07 23:35:48,255 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 545, in query
    with self.patroni.postgresql.connection().cursor() as cursor:
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 244, in connection
    return self._connection.get()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 23, in get
    self._connection = psycopg2.connect(**self._conn_kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 484, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 466, in query
    return self.server.query(sql, *params)
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 551, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: 'connection problems'
2020-10-07 23:35:49,264 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 545, in query
    with self.patroni.postgresql.connection().cursor() as cursor:
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 244, in connection
    return self._connection.get()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 23, in get
    self._connection = psycopg2.connect(**self._conn_kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 484, in get_postgresql_status
    row = self.query(stmt.format(postgresql.wal_name, postgresql.lsn_name), retry=retry)[0]
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 466, in query
    return self.server.query(sql, *params)
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 551, in query
    raise PostgresConnectionException('connection problems')
patroni.exceptions.PostgresConnectionException: 'connection problems'
2020-10-07 23:35:50,273 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 545, in query
    with self.patroni.postgresql.connection().cursor() as cursor:
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 244, in connection
    return self._connection.get()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 23, in get
    self._connection = psycopg2.connect(**self._conn_kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

```
