### ISSUE TITLE
Promote standby cluster has no effect

### ISSUE THREAD

**Issue by Chup4Chups** [CrunchyData/postgres-operator#2043]
**Describe the bug**
After shutdown primary cluster and promote standby the secondary cluster, the pod logs still show "i am the standby leader with the lock"

**To Reproduce**
1. Create primary 
2. Create secondary cluster
3. shutdown primary
4. promote-standby secondary

**Expected behavior**
The secondary become leader and pod logs show " i am the leader with the lock"

**Screenshots**

**Please tell us about your environment:**

* PGO: 4.5.0 
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): S3 (MiniIO)
* Platform (Docker, Kubernetes, OpenShift): v1.16.13

**Additional context**

Hello, we follow documentation available here to test multi cluster deployments.
https://access.crunchydata.com/documentation/postgres-operator/4.5.0/architecture/high-availability/multi-cluster-kubernetes/

We succesfully created primary and secondary cluster with pgo on 2 differents cluster.

However, after shutting down the primary, and promoting the standby, we don't see any update from pod logs on the secondary cluster.

You can see below the steps and logs.

### primary cluster
```
cluster01$> pgo create cluster test -n pgo 
--pgbouncer 
--replica-count=2   
--pgbackrest-storage-type=s3   
--pgbackrest-s3-key=pgo-backrest    
--pgbackrest-s3-key-secret=mysecret
--pgbackrest-s3-uri-style=path    
--pgbackrest-s3-bucket=pgo-backrest   
--pgbackrest-s3-endpoint=miniIO.domain
--pgbackrest-s3-verify-tls 
--pgbackrest-s3-region=fr   
--password-superuser=test   
--password-replication=test 
--password=datalake
```
```
cluster01$> pgo test test
cluster : test
        Services
                primary (xxx:5432): UP
                pgbouncer (xxx:5432): UP
                replica (xxx:5432): UP
        Instances
                primary (test-6dd5786f4d-g9c7t): UP
                replica (test-hnbt-75586fb889-q6hlh): UP
                replica (test-jnqm-869b579f47-llg79): DOWN
```

### secondary cluster
```
cluster02$> pgo create cluster test -n pgo  
--standby  
--pgbouncer 
--replica-count=2   
--pgbackrest-storage-type=s3   
--pgbackrest-s3-key=pgo-backrest    
--pgbackrest-s3-key-secret=mysecret  
--pgbackrest-s3-uri-style=path    
--pgbackrest-s3-bucket=pgo-backrest   
--pgbackrest-s3-endpoint=miniIO.domain  
--pgbackrest-s3-verify-tls 
--pgbackrest-s3-region=fr   
--password-superuser=test   
--password-replication=test 
--password=datalake 
--pgbackrest-repo-path=/backrestrepo/test-backrest-shared-repo
```
```
cluster02$> kubectl logs -n pgo -f test-565d6fc86f-fjpz2
Wed Nov 11 15:05:05 UTC 2020 INFO: standby pgBackRest restore complete
2020-11-11 15:05:05,422 INFO: replica has been created using pgbackrest_standby
2020-11-11 15:05:05,424 INFO: bootstrapped clone from remote master None
2020-11-11 15:05:05,433 WARNING: Removing enum parameter=recovery_target from the config due to the invalid value=
2020-11-11 15:05:05,695 INFO: postmaster pid=541
2020-11-11 15:05:05.699 UTC [541] LOG:  pgaudit extension initialized
2020-11-11 15:05:05.700 UTC [541] LOG:  starting PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
2020-11-11 15:05:05.700 UTC [541] LOG:  listening on IPv4 address "0.0.0.0", port 5432
/tmp:5432 - no response
2020-11-11 15:05:05.719 UTC [541] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-11-11 15:05:05.732 UTC [541] LOG:  listening on Unix socket "/crunchyadm/.s.PGSQL.5432"
2020-11-11 15:05:05.756 UTC [541] LOG:  redirecting log output to logging collector process
2020-11-11 15:05:05.756 UTC [541] HINT:  Future log output will appear in directory "pg_log".
/tmp:5432 - rejecting connections
/tmp:5432 - rejecting connections
2020-11-11 15:05:06,844 INFO: Lock owner: None; I am test-565d6fc86f-fjpz2
2020-11-11 15:05:06,844 INFO: not healthy enough for leader race
2020-11-11 15:05:06,895 INFO: bootstrap_standby_leader in progress
/tmp:5432 - accepting connections
2020-11-11 15:05:07,738 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2020-11-11 15:05:07,743 INFO: Reaped pid=588, exit status=0
2020-11-11 15:05:07,832 INFO: establishing a new patroni connection to the postgres cluster
2020-11-11 15:05:07,931 INFO: initialized a new cluster
Wed Nov 11 15:05:08 UTC 2020 INFO: PGHA_INIT is 'true', waiting to initialize as primary
2020-11-11 15:05:18,238 INFO: Lock owner: test-565d6fc86f-fjpz2; I am test-565d6fc86f-fjpz2
2020-11-11 15:05:18,337 INFO: no action.  i am the standby leader with the lock
2020-11-11 15:05:28,238 INFO: Lock owner: test-565d6fc86f-fjpz2; I am test-565d6fc86f-fjpz2
2020-11-11 15:05:28,285 INFO: no action.  i am the standby leader with the lock
```

### primary cluster shutdown
```
cluster01$> pgo update cluster test --shutdown
cluster01$> pgo test test

cluster : test
        Services
        Instances
                primary (): DOWN
```

### secondary cluster promote
```
cluster02$> pgo update cluster test --promote-standby
cluster02$> kubectl logs -n pgo -f test-565d6fc86f-fjpz2
[...]
2020-11-11 15:10:38,238 INFO: Lock owner: test-565d6fc86f-fjpz2; I am test-565d6fc86f-fjpz2
2020-11-11 15:10:38,286 INFO: no action.  i am the standby leader with the lock
```

We found this issue but it didn't work for us: 
https://github.com/CrunchyData/postgres-operator/issues/1959

```
cluster02$> kubectl exec -it test-565d6fc86f-fjpz2 -n pgo -- ls "/crunchyadm/pgha_initialized"
ls: cannot access /crunchyadm/pgha_initialized: No such file or directory
command terminated with exit code 2

cluster02$> kubectl exec -it test-565d6fc86f-fjpz2 -n pgo -- touch "/crunchyadm/pgha_initialized"
cluster02$> kubectl exec -it test-565d6fc86f-fjpz2 -n pgo -- ls "/crunchyadm/pgha_initialized"
/crunchyadm/pgha_initialized
```

```
cluster02$> kubectl logs -n pgo -f test-565d6fc86f-fjpz2
[...]
2020-11-11 15:13:28,238 INFO: Lock owner: test-565d6fc86f-fjpz2; I am test-565d6fc86f-fjpz2
2020-11-11 15:13:28,286 INFO: no action.  i am the standby leader with the lock
2020-11-11 15:13:38,238 INFO: Lock owner: test-565d6fc86f-fjpz2; I am test-565d6fc86f-fjpz2
2020-11-11 15:13:38,287 INFO: no action.  i am the standby leader with the lock
```
```
cluster02$> kubectl exec -it test-565d6fc86f-fjpz2 -n pgo -- cat /pgdata/test/pg_log/postgresql-Wed.log
2020-11-11 15:05:06.184 UTC [547] LOG:  entering standby mode
2020-11-11 15:05:06.593 UTC [561] FATAL:  the database system is starting up
2020-11-11 15:05:06.714 UTC [564] FATAL:  the database system is starting up
2020-11-11 15:05:06.721 UTC [566] FATAL:  the database system is starting up
2020-11-11 15:05:06.749 UTC [547] LOG:  restored log file "000000010000000000000002" from archive
2020-11-11 15:05:06.976 UTC [547] LOG:  redo starts at 0/2000028
2020-11-11 15:05:06.987 UTC [547] LOG:  consistent recovery state reached at 0/20006A0
2020-11-11 15:05:06.988 UTC [541] LOG:  database system is ready to accept read only connections
2020-11-11 15:05:07.522 UTC [547] LOG:  restored log file "000000010000000000000003" from archive
2020-11-11 15:05:08.239 UTC [547] LOG:  restored log file "000000010000000000000004" from archive
2020-11-11 15:13:16.106 UTC [5391] ERROR:  cannot execute ALTER ROLE in a read-only transaction
```

**Comment by jkatz** [comment]
[4.5.1](https://github.com/CrunchyData/postgres-operator/releases/tag/v4.5.1) was recently released that includes the explicit bugfix referenced in #1959 -- I'd recommend trying again.

**Comment by Chup4Chups** [comment]
Just retried with new release 4.5.1.
The primary cluster is created succesfully.
The secondary failed during bootstrap.

```
2020-11-16 12:10:38,400 INFO: not healthy enough for leader race
2020-11-16 12:10:38,400 INFO: bootstrap_standby_leader in progress
2020-11-16 12:10:48,400 INFO: Lock owner: None; I am test-bc7f556bc-8v8tv
2020-11-16 12:10:48,400 INFO: not healthy enough for leader race
2020-11-16 12:10:48,400 INFO: bootstrap_standby_leader in progress
ERROR: [125]: remote-0 process on 'test-backrest-shared-repo' terminated unexpectedly [255]: ssh: connect to host test-backrest-shared-repo port 2022: Connection timed out
Mon Nov 16 12:10:55 UTC 2020 ERROR: pgBackRest standby Creation: pgBackRest restore failed when creating standby
2020-11-16 12:10:55,282 ERROR: Error creating replica using method pgbackrest_standby: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh standby exited with code=125
2020-11-16 12:10:55,282 ERROR: failed to bootstrap clone from remote master None
2020-11-16 12:10:55,283 INFO: Removing data directory: /pgdata/test
2020-11-16 12:10:58,400 INFO: removing initialize key after failed attempt to bootstrap the cluster
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```
