### ISSUE TITLE
Can't restore from Digital Ocean Spaces (s3) backup

### ISSUE THREAD

**Issue by jfmatth** [CrunchyData/postgres-operator#2128]
**Describe the bug**
Trying to restore from a backup in Digital Ocean Spaces, I get an error not able to verify certificate

**To Reproduce**
Backups are occurring fine to Spaces(s3), with the config using
```
pgo create cluster sotb-v1-prod --pgbackrest-storage-type s3 --pgbackrest-s3-bucket pgo-backup --pgbackrest-s3-endpoint sfo2.digitaloceanspaces.com --pgbackrest-s3-region sfo2 --pgbackrest-s3-uri-style path --pgbackrest-s3-key xxxx --pgbackrest-s3-key-secret xxxxxxxxxxx --pgbackrest-pvc-size 3Gi --pvc-size 3Gi --pgbackrest-s3-verify-tls=false --database sotb
```
Can't restore to another cluster with 
```
pgo create cluster clone --pgbackrest-pvc-size 3Gi --pvc-size 3Gi --restore-opts="--repo-type=s3" --restore-from sotb-v1-prod --database sotb --username adminsyymgnc
```

**Expected behavior**
A restore of cluster to new cluster

**Please tell us about your environment:**

* Digital Ocean Kubernetes 1.18
* Where is this running Digital Ocean
* Storage being used Local and backups in S3
* Container Image Tag: registry.developers.crunchydata.com/crunchydata/pgo-apiserver:centos7-4.5.1
* PostgreSQL Version: 12.5?
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: 4.5.1

**Additional context**

I tried setting --restore-opts='--repo-s3-validate-ssl=n' but that didn't work, errored in bootstrap with bad option

Logs from the bootstrap pod

```
Wed Dec 16 01:47:42 UTC 2020 INFO: Empty PGDATA dir found for primary, a non-delta restore will be peformed
2020-12-16 01:47:52,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:47:52,865 INFO: not healthy enough for leader race
2020-12-16 01:47:52,931 INFO: bootstrap in progress
2020-12-16 01:48:02,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:48:02,865 INFO: not healthy enough for leader race
2020-12-16 01:48:02,865 INFO: bootstrap in progress
2020-12-16 01:48:12,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:48:12,865 INFO: not healthy enough for leader race
2020-12-16 01:48:12,865 INFO: bootstrap in progress
2020-12-16 01:48:22,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:48:22,865 INFO: not healthy enough for leader race
2020-12-16 01:48:22,865 INFO: bootstrap in progress
2020-12-16 01:48:32,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:48:32,865 INFO: not healthy enough for leader race
2020-12-16 01:48:32,865 INFO: bootstrap in progress
2020-12-16 01:48:42,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:48:42,865 INFO: not healthy enough for leader race
2020-12-16 01:48:42,865 INFO: bootstrap in progress
2020-12-16 01:48:52,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:48:52,865 INFO: not healthy enough for leader race
2020-12-16 01:48:52,865 INFO: bootstrap in progress
2020-12-16 01:49:02,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:49:02,865 INFO: not healthy enough for leader race
2020-12-16 01:49:02,865 INFO: bootstrap in progress
2020-12-16 01:49:12,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:49:12,865 INFO: not healthy enough for leader race
2020-12-16 01:49:12,865 INFO: bootstrap in progress
2020-12-16 01:49:22,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:49:22,865 INFO: not healthy enough for leader race
2020-12-16 01:49:22,865 INFO: bootstrap in progress
2020-12-16 01:49:32,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:49:32,865 INFO: not healthy enough for leader race
2020-12-16 01:49:32,865 INFO: bootstrap in progress
2020-12-16 01:49:42,865 INFO: Lock owner: None; I am clone-bootstrap-tqdjj
2020-12-16 01:49:42,865 INFO: not healthy enough for leader race
2020-12-16 01:49:42,865 INFO: bootstrap in progress
ERROR: [095]: unable to load info file '/backrestrepo/sotb-v1-prod-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/sotb-v1-prod-backrest-shared-repo/backup/db/backup.info.copy':
       CryptoError: raised from remote-0 protocol on 'sotb-v1-prod-backrest-shared-repo': unable to verify certificate presented by 'sfo2.digitaloceanspaces.com:443': [20] unable to get local issuer certificate
       HINT: is or was the repo encrypted?
       CryptoError: raised from remote-0 protocol on 'sotb-v1-prod-backrest-shared-repo': unable to verify certificate presented by 'sfo2.digitaloceanspaces.com:443': [20] unable to get local issuer certificate
       HINT: is or was the repo encrypted?
       HINT: backup.info cannot be opened and is required to perform a backup.
       HINT: has a stanza-create been performed?
Wed Dec 16 01:49:43 UTC 2020 ERROR: pgBackRest primary Creation: pgBackRest restore failed when creating primary
2020-12-16 01:49:43,242 INFO: removing initialize key after failed attempt to bootstrap the cluster
2020-12-16 01:49:43,292 INFO: renaming data directory to /pgdata/clone_2020-12-16-01-49-43
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'

```

**Comment by jkatz** [comment]
Did you try passing in `--pgbackrest-s3-verify-tls=false ` on the restore command?

Do you have Digital Ocean's CA bundle available? You can use it by setting the value if the `aws-s3-ca.crt` in the `pgo-backrest-repo-config` Secret.

**Comment by jfmatth** [comment]
@jkatz Jonathan, thanks for the **SUPER** quick response.

Where is that option listed?  I've searched up and down and can't find it anywhere?

I'll definitely try that now and let you know.

I can probably get their cert, but for now, just getting this to work would make my day.  What's odd, is if I goto the endpoint, the cert show's valid, but maybe in a K8s cluster it's not able to find the root CA?

**Comment by jfmatth** [comment]
@jkatz 

Sadly, it didn't work, same error

here's what i did

```
pgo create cluster clone --pgbackrest-pvc-size 3Gi --pvc-size 3Gi --pgbackrest-s3-verify-tls=false --restore-opts='--repo-type=s3' --restore-from sotb-v1-prod --database sotb --username adminsyymgnc
```
Logs are the same from the bootstrap
```
020-12-16 02:26:34,698 INFO: not healthy enough for leader race
2020-12-16 02:26:34,698 INFO: bootstrap in progress
ERROR: [095]: unable to load info file '/backrestrepo/sotb-v1-prod-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/sotb-v1-prod-backrest-shared-repo/backup/db/backup.info.copy':
       CryptoError: raised from remote-0 protocol on 'sotb-v1-prod-backrest-shared-repo': unable to verify certificate presented by 'sfo2.digitaloceanspaces.com:443': [20] unable to get local issuer certificate
       HINT: is or was the repo encrypted?
       CryptoError: raised from remote-0 protocol on 'sotb-v1-prod-backrest-shared-repo': unable to verify certificate presented by 'sfo2.digitaloceanspaces.com:443': [20] unable to get local issuer certificate
       HINT: is or was the repo encrypted?
       HINT: backup.info cannot be opened and is required to perform a backup.
       HINT: has a stanza-create been performed?
Wed Dec 16 02:26:35 UTC 2020 ERROR: pgBackRest primary Creation: pgBackRest restore failed when creating primary
2020-12-16 02:26:35,377 INFO: removing initialize key after failed attempt to bootstrap the cluster
2020-12-16 02:26:35,427 INFO: renaming data directory to /pgdata/clone_2020-12-16-02-26-35
```

**Comment by jkatz** [comment]
pgBackRest has an option `--no-repo-s3-verify-tls` that would be a candidate for `--restore-opts` but that is on an exclude-list, as we provide the top-level option.

If the goal is to get this to work and make your day, I would suggest providing the certificate of the endpoint. This can be done using the `--pgbackrest-s3-ca-secret` flag on [`pgo create cluster`](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/reference/pgo_create_cluster/) (note the key name of `aws-s3-ca.crt` this was designed when pgBackRest only supported S3 and needs to be rewritten at some point).

The other methods is as stated in [https://github.com/CrunchyData/postgres-operator/issues/2128#issuecomment-745715779](https://github.com/CrunchyData/postgres-operator/issues/2128#issuecomment-745715779): provide that to the `pgo-backrest-repo-config` Secret and restart the `postgres-operator` Pod and see if that does the trick.

There may be the potential for new development here to support the no TLS verification case, though pgBackRest does work best with TLS.

**Comment by jfmatth** [comment]
Thank you for the quick response at such a late hour @jkatz 

My question now, is where to get the certs, do i just need to save them to a file from openssl or something?  Never done that before, but that's what google is for 👍 

I do agree that having the cert in the config makes the most sense, but i'm still testing so didn't think it mattered.

I'll try adding it to the cert tonight and see if that work.

Thanks again for all your help here,

**Comment by janosroden** [comment]
@jfmatth I was able to setup both backup and restore with the aws secret (pgo 4.5.1):

I had to extract the local root cert and save to the secret (on OS X):
`sudo security verify-cert -P https://ams3.digitaloceanspaces.com`
Save the last to a file and then
`kubectl create secret generic -n pgo --from-file=aws-s3-ca.crt=./all.crt digicert`

Then on cluster create use `--pgbackrest-s3-ca-secret digicert`

<details>
  <summary>My local DigiCert root cert</summary>

```
$ openssl x509 -text < all.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            08:3b:e0:56:90:42:46:b1:a1:75:6a:c9:59:91:c7:4a
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
        Validity
            Not Before: Nov 10 00:00:00 2006 GMT
            Not After : Nov 10 00:00:00 2031 GMT
        Subject: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:e2:3b:e1:11:72:de:a8:a4:d3:a3:57:aa:50:a2:
                    8f:0b:77:90:c9:a2:a5:ee:12:ce:96:5b:01:09:20:
                    cc:01:93:a7:4e:30:b7:53:f7:43:c4:69:00:57:9d:
                    e2:8d:22:dd:87:06:40:00:81:09:ce:ce:1b:83:bf:
                    df:cd:3b:71:46:e2:d6:66:c7:05:b3:76:27:16:8f:
                    7b:9e:1e:95:7d:ee:b7:48:a3:08:da:d6:af:7a:0c:
                    39:06:65:7f:4a:5d:1f:bc:17:f8:ab:be:ee:28:d7:
                    74:7f:7a:78:99:59:85:68:6e:5c:23:32:4b:bf:4e:
                    c0:e8:5a:6d:e3:70:bf:77:10:bf:fc:01:f6:85:d9:
                    a8:44:10:58:32:a9:75:18:d5:d1:a2:be:47:e2:27:
                    6a:f4:9a:33:f8:49:08:60:8b:d4:5f:b4:3a:84:bf:
                    a1:aa:4a:4c:7d:3e:cf:4f:5f:6c:76:5e:a0:4b:37:
                    91:9e:dc:22:e6:6d:ce:14:1a:8e:6a:cb:fe:cd:b3:
                    14:64:17:c7:5b:29:9e:32:bf:f2:ee:fa:d3:0b:42:
                    d4:ab:b7:41:32:da:0c:d4:ef:f8:81:d5:bb:8d:58:
                    3f:b5:1b:e8:49:28:a2:70:da:31:04:dd:f7:b2:16:
                    f2:4c:0a:4e:07:a8:ed:4a:3d:5e:b5:7f:a3:90:c3:
                    af:27
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier:
                03:DE:50:35:56:D1:4C:BB:66:F0:A3:E2:1B:1B:C3:97:B2:3D:D1:55
            X509v3 Authority Key Identifier:
                keyid:03:DE:50:35:56:D1:4C:BB:66:F0:A3:E2:1B:1B:C3:97:B2:3D:D1:55

    Signature Algorithm: sha1WithRSAEncryption
         cb:9c:37:aa:48:13:12:0a:fa:dd:44:9c:4f:52:b0:f4:df:ae:
         04:f5:79:79:08:a3:24:18:fc:4b:2b:84:c0:2d:b9:d5:c7:fe:
         f4:c1:1f:58:cb:b8:6d:9c:7a:74:e7:98:29:ab:11:b5:e3:70:
         a0:a1:cd:4c:88:99:93:8c:91:70:e2:ab:0f:1c:be:93:a9:ff:
         63:d5:e4:07:60:d3:a3:bf:9d:5b:09:f1:d5:8e:e3:53:f4:8e:
         63:fa:3f:a7:db:b4:66:df:62:66:d6:d1:6e:41:8d:f2:2d:b5:
         ea:77:4a:9f:9d:58:e2:2b:59:c0:40:23:ed:2d:28:82:45:3e:
         79:54:92:26:98:e0:80:48:a8:37:ef:f0:d6:79:60:16:de:ac:
         e8:0e:cd:6e:ac:44:17:38:2f:49:da:e1:45:3e:2a:b9:36:53:
         cf:3a:50:06:f7:2e:e8:c4:57:49:6c:61:21:18:d5:04:ad:78:
         3c:2c:3a:80:6b:a7:eb:af:15:14:e9:d8:89:c1:b9:38:6c:e2:
         91:6c:8a:ff:64:b9:77:25:57:30:c0:1b:24:a3:e1:dc:e9:df:
         47:7c:b5:b4:24:08:05:30:ec:2d:bd:0b:bf:45:bf:50:b9:a9:
         f3:eb:98:01:12:ad:c8:88:c6:98:34:5f:8d:0a:3c:c6:e9:d5:
         95:95:6d:de
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
-----END CERTIFICATE-----
```
</details>

**Comment by jfmatth** [comment]
@janosroden Wow, thank you.

I eventually gave up and went back to local DO volumes, but when i get around, i'm gonna try this solution.  Thank you very much for following up.
