### ISSUE TITLE
DB container fails in hippo cluster

### ISSUE THREAD

**Issue by rj9333** [CrunchyData/postgres-operator#2238]
We are running postgres operator in GKE cluster
Postgres operator and hippo primary pod is running fine and replica pod is not able to starts its database container. 
Shows below error.
psql: error: could not connect to server: FATAL:  the database system is starting up

What could be the reason and how do we resolve this issue?

Logs: 

2021-01-29 10:04:10,874 ERROR: get_postgresql_status
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/api.py", line 498, in query
    with self.patroni.postgresql.connection().cursor() as cursor:
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 228, in connection
    return self._connection.get()
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 23, in get
    self._connection = psycopg2.connect(**self._conn_kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

**Comment by jkatz** [comment]
- How did you create the cluster?
- How did you set up your storage configuration?
- Are there errors in your Operator logs?
- Are there errors in your Kubernetes environment?

**Comment by rj9333** [comment]
Closing this- we addressed it
