### ISSUE TITLE
Crash on 4.6.0 while calling create cluster API (apiserver)

### ISSUE THREAD

**Issue by JeffreyDD** [CrunchyData/postgres-operator#2262]
**Describe the bug**
Operator API crashes while attempting to create cluster by calling API directly.

**To Reproduce**
1. Create a cluster using the PGO `/clusters` endpoint (using Ansible in our case)
```
fatal: [kind-kind]: FAILED! => {
    "changed": false,
    "connection": "close",
    "content_length": "150",
    "content_type": "text/html",
    "date": "Mon, 08 Feb 2021 14:03:02 GMT",
    "elapsed": 0,
    "invocation": {
        "module_args": {
            "attributes": null,
            "body": {
                "AutofailFlag": true,
                "BackrestS3Bucket": "xxx",
                "BackrestS3CASecretName": "letsencrypt-issuer",
                "BackrestS3Endpoint": "backup.xxx",
                "BackrestS3Key": "xxx",
                "BackrestS3KeySecret": "xxx",
                "BackrestS3Region": "minio",
                "BackrestS3URIStyle": "path",
                "BackrestStorageType": "local,s3",
                "ClientVersion": "4.6.0",
                "MetricsFlag": true,
                "Name": "xxx",
                "Namespace": "xxx",
                "Password": "xxx",
                "PasswordReplication": "xxx",
                "PasswordSuperuser": "xxx"
            },
            "body_format": "json",
            "client_cert": null,
            "client_key": null,
            "creates": null,
            "dest": null,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": true,
            "group": null,
            "headers": {
                "Content-Type": "application/json"
            },
            "http_agent": "ansible-httpget",
            "method": "POST",
            "mode": null,
            "owner": null,
            "remote_src": false,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "200"
            ],
            "timeout": 30,
            "unix_socket": null,
            "unsafe_writes": false,
            "url": "https://xxx/clusters",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "admin",
            "use_proxy": true,
            "validate_certs": false
        }
    },
    "msg": "Status code was 502 and not [200]: HTTP Error 502: Bad Gateway",
    "redirected": false,
    "status": 502,
    "strict_transport_security": "max-age=15724800; includeSubDomains",
    "url": "https://xxx/clusters"
}
```

2. Panic in `apiserver` log, request fails
```
time="2021-02-08T12:38:44Z" level=info msg="listening on port 8443" func="main.main()" file="cmd/apiserver/main.go:167" version=4.6.0
2021/02/08 13:54:03 http: panic serving 10.244.1.14:49956: assignment to entry in nil map
goroutine 15450 [running]:
net/http.(*conn).serve.func1(0xc0003a2500)
    /usr/lib/golang/src/net/http/server.go:1801 +0x147
panic(0x1598580, 0x195f130)
    /usr/lib/golang/src/runtime/panic.go:975 +0x47a
github.com/crunchydata/postgres-operator/internal/apiserver/clusterservice.getClusterParams(0xc0006c2000, 0xc000406d20, 0xd, 0xc000406cd0, 0xf, 0x0)
    /opt/cdev/src/github.com/crunchydata/postgres-operator/internal/apiserver/clusterservice/clusterimpl.go:1362 +0xf07
github.com/crunchydata/postgres-operator/internal/apiserver/clusterservice.CreateCluster(0xc0006c2000, 0xc000406cd0, 0xf, 0xc0005944c0, 0x5, 0x0, 0x0
    /opt/cdev/src/github.com/crunchydata/postgres-operator/internal/apiserver/clusterservice/clusterimpl.go:855 +0xe18
github.com/crunchydata/postgres-operator/internal/apiserver/clusterservice.CreateClusterHandler(0x19a68a0, 0xc000185260, 0xc00043c800)
    /opt/cdev/src/github.com/crunchydata/postgres-operator/internal/apiserver/clusterservice/clusterservice.go:90 +0x7aa
net/http.HandlerFunc.ServeHTTP(0x17db960, 0x19a68a0, 0xc000185260, 0xc00043c800)
    /usr/lib/golang/src/net/http/server.go:2042 +0x44
github.com/crunchydata/postgres-operator/internal/apiserver.(*certEnforcer).Enforce.func1(0x19a68a0, 0xc000185260, 0xc00043c800)
    /opt/cdev/src/github.com/crunchydata/postgres-operator/internal/apiserver/middleware.go:66 +0xb5
net/http.HandlerFunc.ServeHTTP(0xc0000bb060, 0x19a68a0, 0xc000185260, 0xc00043c800)
    /usr/lib/golang/src/net/http/server.go:2042 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00016c3c0, 0x19a68a0, 0xc000185260, 0xc00043c600)
    /opt/cdev/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc000184380, 0x19a68a0, 0xc000185260, 0xc00043c600)
    /usr/lib/golang/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0003a2500, 0x19a9a20, 0xc00062e440)
    /usr/lib/golang/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
    /usr/lib/golang/src/net/http/server.go:2969 +0x36c
```

**Expected behavior**
A `pgcluster` to be created

**Please tell us about your environment:**

* Operating System: MacOS
* Where is this running ( Local, Cloud Provider): Local (Kind)
* Storage being used (NFS, Hostpath, Gluster, etc): NFS
* Container Image Tag: 4.6.0
* PostgreSQL Version: N/A
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: `Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}`

**Additional context**
This is probably related to API changes between 4.5.0 and 4.6.0, but still the `apiserver` shouldnt panic like this and instead return a decent error.

**Comment by jkatz** [comment]
@JeffreyDD That is certainly a bug an an easy fix to apply for 4.6.1, which will be released in the coming weeks. Thanks for reporting!

If you need a workaround, pass `{}` to `UserLabels` in the API.
