### ISSUE TITLE
pgo restore does not honor disabled SSL verification for S3 storage location

### ISSUE THREAD

**Issue by bo0ts** [CrunchyData/postgres-operator#2498]
## Overview

Trying to restore a database when backups have been taken with disabled SSL verification fails.

## Environment

Please provide the following details:

- OKD 4.5
- postgres-operator 4.6.2

### REPRO

Create cluster with following S3 config:

```
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  name: foo
spec:
  backrestRepoPath: ""
  backrestS3Bucket: backup
  backrestS3Endpoint: X.X.X.X:9000
  backrestS3Region: us-east-1
  backrestS3URIStyle: path
  backrestS3VerifyTLS: "false"
  backrestStorageTypes:
  - s3
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos7-12.5-4.6.2
  clustername: postgresql-foo
  customconfig: postgresql-foo-cluster-config
  database: postgresql-foo
```

Run a backup and verify backup:

```
sh-4.4$ pgo show backup foo

cluster: foo
storage type: s3

stanza: db
    status: ok
    cipher: none

    db (current)
        wal archive min/max (13-1)

        full backup: 20210615-114354F
            timestamp start/stop: 2021-06-15 11:43:54 +0000 UTC / 2021-06-15 11:44:34 +0000 UTC
            wal start/stop: 000000010000000000000002 / 000000010000000000000002
            database size: 31.1MiB, backup size: 31.1MiB
            repository size: 3.8MiB, repository backup size: 3.8MiB
            backup reference list: 

        incr backup: 20210615-114354F_20210615-120035I
            timestamp start/stop: 2021-06-15 12:00:35 +0000 UTC / 2021-06-15 12:00:38 +0000 UTC
            wal start/stop: 000000010000000000000006 / 000000010000000000000007
            database size: 31.2MiB, backup size: 1.8MiB
            repository size: 3.8MiB, repository backup size: 245.4KiB
            backup reference list: 20210615-114354F

        incr backup: 20210615-114354F_20210615-120431I
            timestamp start/stop: 2021-06-15 12:04:31 +0000 UTC / 2021-06-15 12:07:35 +0000 UTC
            wal start/stop: 00000001000000000000001D / 000000010000000000000020
            database size: 348.9MiB, backup size: 325.8MiB
            repository size: 192.9MiB, repository backup size: 190.1MiB
            backup reference list: 20210615-114354F, 20210615-114354F_20210615-120035I
```

Run a restore:

```
sh-4.4$  pgo restore foo --pgbackrest-storage-type s3
```

Failure while bootstrapping:

```
2021-06-15 13:48:01,799 INFO: bootstrap in progress
ERROR: [095]: unable to load info file '/backrestrepo/foo-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/foo-backrest-shared-repo/backup/db/backup.info.copy':
       CryptoError: raised from remote-0 protocol on 'foo-backrest-shared-repo': unable to verify certificate presented by '10.127.0.11:9000': [18] self signed certificate
       HINT: is or was the repo encrypted?
       CryptoError: raised from remote-0 protocol on 'foo-backrest-shared-repo': unable to verify certificate presented by '10.127.0.11:9000': [18] self signed certificate
       HINT: is or was the repo encrypted?
       HINT: backup.info cannot be opened and is required to perform a backup.
       HINT: has a stanza-create been performed?
[0;31mTue Jun 15 13:48:11 UTC 2021 ERROR: pgBackRest primary Creation: pgBackRest restore failed when creating primary[0m
2021-06-15 13:48:11,740 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-06-15 13:48:11,790 INFO: renaming data directory to /pgdata/foo_2021-06-15-13-48-11
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1457, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1351, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1247, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1240, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

I've tried adding several options to `--backup-opts` but neither worked. pgo restore cannot be passed ` --pgbackrest-s3-verify-tls=false`.

To me it looks like the following lines in `/opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh` is responsible: 

```
if [[ -f /pgconf/replica-bootstrap-repo-type ]]
then
    replica_bootstrap_repo_type="$(cat /pgconf/replica-bootstrap-repo-type)"
    if [[ "${replica_bootstrap_repo_type}" != "" ]]
    then
        restore_cmd_args+=("--repo1-type=${replica_bootstrap_repo_type}")
    fi
fi

# for an S3 repo, if TLS verification is disabled, pass in the appropriate flag
# otherwise, leave the default behavior and verify the S3 server certificate
if [[ ${replica_bootstrap_repo_type} == "s3" && ${PGHA_PGBACKREST_S3_VERIFY_TLS} == "false" ]]
then
    restore_cmd_args+=("--no-repo1-s3-verify-tls")
fi
```

The file `/pgconf/replica-bootstrap-repo-type` does not exist. I can provide the job configuration if that would help.

### Expected outcome

I would expect a restore to work since a backup also worked.

**Comment by jkatz** [comment]
I would suggest upgrading to 4.6.3 as there was a [fix related to a similar issue](https://github.com/CrunchyData/postgres-operator/issues/2314).

If it doesn't not work after the upgrade, we can investigate further if there is a bug.
