### ISSUE TITLE
Restoring from S3

### ISSUE THREAD

**Issue by JanCizmar** [CrunchyData/postgres-operator#2504]
Hello,

I had pgo v4.5.1 installed, while I found out, that my backups are failing due to inability to pull v4.5.1 image. I tried to update to 4.7.0, but then my cluster didn't start. After many tries I could not recover my cluster from my backups located in s3 repository. I am following this thread: https://github.com/CrunchyData/postgres-operator/issues/1305

I am kind of trapped, since I cannot download any crunchy-postgres-ha image, supporting postgres v12.5. I found some older images on docker-hub, but I am getting this error in postgres pod: 

```
2021-06-19 18:34:24,647 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-06-19 18:34:24,653 INFO: Lock owner: None; I am hippo-85d85bc895-n84pm
2021-06-19 18:34:24,716 INFO: trying to bootstrap a new standby leader
Sat Jun 19 18:34:24 UTC 2021 INFO: Empty PGDATA dir found for replica, a non-delta restore will be peformed
ERROR: [039]: expected value '2.25' for greeting key 'version' but got '2.29'
Sat Jun 19 18:34:25 UTC 2021 ERROR: pgBackRest Replica Creation: pgBackRest restore failed when creating replica
2021-06-19 18:34:25,209 ERROR: Error creating replica using method pgbackrest_standby: /opt/cpm/bin/pgbackrest/pgbackrest-create-replica.sh exited with code=39
2021-06-19 18:34:25,210 ERROR: failed to bootstrap clone from remote master None
2021-06-19 18:34:25,210 INFO: Removing data directory: /pgdata/hippo
2021-06-19 18:34:34,654 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-06-19 18:34:35,077 INFO: Lock owner: None; I am hippo-85d85bc895-n84pm
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 199, in patroni_main
    patroni.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 135, in run
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1370, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1277, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1173, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1168, in cancel_initialization
    raise PatroniException('Failed to bootstrap cluster')
patroni.exceptions.PatroniException: 'Failed to bootstrap cluster'
```

What are my options to restore it?

Thanks.

**Comment by jkatz** [comment]
The PostgreSQL 12 containers are still available in the [Developer Portal](https://www.crunchydata.com/developers/download-postgres/containers) using a CentOS 8 image. The CentOS 7 containers were dropped; these were deprecated back in December 2020 with multiple notices on the [developer portal website](https://www.crunchydata.com/developers/download-postgres/containers) and to the [developer portal mailing list](https://www.crunchydata.com/developers/newsletter).
