### ISSUE TITLE
Errors when recovering with backrest from s3.

### ISSUE THREAD

**Issue by dmrost** [CrunchyData/postgres-operator#2508]
## Environment
- Platform: OpenShift
- Platform Version: 4.7
- PGO Image Tag: centos8-13.2-4.6.2
- Postgres Version 13
- Storage: pvc

I can create new cluster and make backup with pgbackrest on s3 but can't restore.
Now i'm trying restore cluster in OpenShift (4.7), via pg_backrest from local s3 or "--restore-from" current cluster

for example:
```
pgo create cluster standby-test \
  --restore-from test-db \
  --pgbackrest-storage-type=s3 \
  --pgbackrest-s3-key=test-backup-user \
  --pgbackrest-s3-key-secret=%%%%%%%% \
  --pgbackrest-s3-bucket=test-db-backup \
  --pgbackrest-s3-endpoint=s3.my_site.com \
  --pgbackrest-s3-region=%%%% \
  --pgbackrest-s3-uri-style=path \
  --pgbackrest-s3-verify-tls=false \
  --password-superuser="%%%%%" \
  --password-replication="%%%%%" \
  --database test-db \
  --username test-user \
  --password="%%%%" 
```
or
```
pgo create cluster standby-test \
  --standby \
  --pgbouncer \
  --password-superuser=%%%% \
  --password-replication=%%%% \
  --database test-db \
  --username test-user \
  --password=%%%% \
  --pgbackrest-storage-type=s3 \
  --pgbackrest-repo-path=/backrestrepo/test-db-backrest-shared-repo \
  --pgbackrest-s3-key=test-backup-user \
  --pgbackrest-s3-key-secret=%%%%% \
  --pgbackrest-s3-bucket=test-db-backup \
  --pgbackrest-s3-endpoint=s3.my_site.com \
  --pgbackrest-s3-region=nlmk \
  --pgbackrest-s3-uri-style=path \
  --pgbackrest-s3-verify-tls=false
```
(Earlier, I make a backup database in /backrestrepo/test-db-backrest-shared-repo)

```
...
[0;33mTue Jun 22 16:30:16 UTC 2021 WARN: Detected an earlier failed attempt to initialize[0m
[0;32mTue Jun 22 16:30:16 UTC 2021 INFO: Correct the issue, remove '/pgdata/standby-test-db.initializing', and try again[0m
[0;32mTue Jun 22 16:30:16 UTC 2021 INFO: Your data might be in: /pgdata/standby-test-db_*[0m
[0;33mTue Jun 22 16:30:26 UTC 2021 WARN: Detected an earlier failed attempt to initialize[0m
[0;32mTue Jun 22 16:30:26 UTC 2021 INFO: Correct the issue, remove '/pgdata/standby-test-db.initializing', and try again[0m
[0;32mTue Jun 22 16:30:26 UTC 2021 INFO: Your data might be in: /pgdata/standby-test-db_*[0m
...
```
But if i create a new cluster (without restore) - cluster is correctly created and working.

Also, when i run pgo with "--restore-from" create a second pod with error:
```
...
2021-06-22 16:02:17,996 INFO: Running custom bootstrap script: /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh primary
[0;32mTue Jun 22 16:02:18 UTC 2021 INFO: Empty PGDATA dir found for primary, a non-delta restore will be peformed[0m
ERROR: [055]: unable to load info file '/backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info.copy':
       FileMissingError: raised from remote-0 protocol on 'test-db-backrest-shared-repo': unable to open missing file '/backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info' for read
       FileMissingError: raised from remote-0 protocol on 'test-db-backrest-shared-repo': unable to open missing file '/backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info.copy' for read
       HINT: backup.info cannot be opened and is required to perform a backup.
       HINT: has a stanza-create been performed?
[0;31mTue Jun 22 16:02:18 UTC 2021 ERROR: pgBackRest primary Creation: pgBackRest restore failed when creating primary[0m
2021-06-22 16:02:18,286 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-06-22 16:02:18,334 INFO: renaming data directory to /pgdata/standby-test-db_2021-06-22-16-02-18
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1457, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1351, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1247, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1240, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```
Although /backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info exists, and i can download this file with my creds.

I am completely confused with this problem.

**Comment by cap1984** [comment]
Been there(

It won't work with remote storage like s3. Backup should be stored locally at `some-name-backrest-shared-repo` pod.

**Comment by jkatz** [comment]
The issue is identified here:

```
�[0;32mTue Jun 22 16:02:18 UTC 2021 INFO: Empty PGDATA dir found for primary, a non-delta restore will be peformed�[0m
ERROR: [055]: unable to load info file '/backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info' or '/backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info.copy':
       FileMissingError: raised from remote-0 protocol on 'test-db-backrest-shared-repo': unable to open missing file '/backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info' for read
       FileMissingError: raised from remote-0 protocol on 'test-db-backrest-shared-repo': unable to open missing file '/backrestrepo/test-db-backrest-shared-repo/backup/db/backup.info.copy' for read
       HINT: backup.info cannot be opened and is required to perform a backup.
       HINT: has a stanza-create been performed?
```

The initial backup was never taken. Please ensure that it is created before attempting a restore. Sometimes this can take time based on network latency, size of backups, etc.

You can check on the status of your backups using the `pgo show backup` command.

> It won't work with remote storage like s3. 

This may depend on your configuration and ensuring you are using the settings correctly. The procedure for doing so is documented in several places, including:

[https://access.crunchydata.com/documentation/postgres-operator/4.7.0/architecture/provisioning/#provisioning-using-a-backup-from-an-another-postgresql-cluster](https://access.crunchydata.com/documentation/postgres-operator/4.7.0/architecture/provisioning/#provisioning-using-a-backup-from-an-another-postgresql-cluster)

and I can confirm we have many reported cases of this working successfully in production environments! 😄

**Comment by dmrost** [comment]
@jkatzt 
It seemed to me that I had tested such a scenario before, but perhaps I was doing something wrong.
Thank you! It works.
