### ISSUE TITLE
Can I retrieve data from a PV?

### ISSUE THREAD

**Issue by arezk84** [CrunchyData/postgres-operator#2612]
I have an old cluster that was working on version  4.6.0
I faced a disk full issue and I resolved it by creating a new cluster from the old one. then it turned that the newly created one doesn't have all the data from the old one.
I have tried to resize the old PV to make the old cluster working again but didn't work.
What I have done is resized the PV and update the deployment but it keeps crashing, the logs from created pod 

error `FATAL:  could not write to file "pg_wal/xlogtemp.139": No space left on device`

the full log
```
Mon Aug 16 07:08:16 UTC 2021 INFO: postgres-ha pre-bootstrap starting...
Mon Aug 16 07:08:16 UTC 2021 INFO: pgBackRest auto-config disabled
Mon Aug 16 07:08:16 UTC 2021 INFO: PGHA_PGBACKREST_LOCAL_S3_STORAGE and PGHA_PGBACKREST_INITIALIZE will be ignored if provided
Mon Aug 16 07:08:16 UTC 2021 INFO: Defaults have been set for the following postgres-ha auto-configuration env vars: PGHA_DEFAULT_CONFIG, PGHA_BASE_BOOTSTRAP_CONFIG, PGHA_BASE_PG_CONFIG
Mon Aug 16 07:08:16 UTC 2021 INFO: Defaults have been set for the following postgres-ha env vars: PGHA_PATRONI_PORT
Mon Aug 16 07:08:16 UTC 2021 INFO: Defaults have been set for the following Patroni env vars: PATRONI_NAME, PATRONI_RESTAPI_LISTEN, PATRONI_RESTAPI_CONNECT_ADDRESS, PATRONI_POSTGRESQL_LISTEN, PATRONI_POSTGRESQL_CONNECT_ADDRESS
Mon Aug 16 07:08:16 UTC 2021 INFO: Setting postgres-ha configuration for database user credentials
Mon Aug 16 07:08:16 UTC 2021 INFO: Setting 'pguser' credentials using file system
Mon Aug 16 07:08:16 UTC 2021 INFO: Setting 'superuser' credentials using file system
Mon Aug 16 07:08:16 UTC 2021 INFO: Setting 'replicator' credentials using file system
Mon Aug 16 07:08:16 UTC 2021 INFO: Applying base bootstrap config to postgres-ha configuration
Mon Aug 16 07:08:16 UTC 2021 INFO: Applying base postgres config to postgres-ha configuration
Mon Aug 16 07:08:16 UTC 2021 INFO: Applying pgbackrest config to postgres-ha configuration
Mon Aug 16 07:08:16 UTC 2021 INFO: Applying standard (non-TLS) remote connection configuration to pg_hba.conf
Mon Aug 16 07:08:16 UTC 2021 INFO: Custom postgres-ha configuration file not detected
Mon Aug 16 07:08:16 UTC 2021 INFO: Finished building postgres-ha configuration file '/tmp/postgres-ha-bootstrap.yaml'
Mon Aug 16 07:08:16 UTC 2021 INFO: postgres-ha pre-bootstrap complete!  The following configuration will be utilized to initialize
******************************
postgres-ha (PGHA) env vars:
******************************
PGHA_BASE_PG_CONFIG=true
PGHA_PATRONI_PORT=8009
PGHA_PG_PORT=5432
PGHA_PGBACKREST_LOCAL_S3_STORAGE=false
PGHA_SYNC_REPLICATION=false
PGHA_USER=postgres
PGHA_INIT=false
PGHA_DEFAULT_CONFIG=true
PGHA_REPLICA_REINIT_ON_START_FAIL=true
PGHA_PGBACKREST=true
PGHA_BASE_BOOTSTRAP_CONFIG=true
PGHA_STANDBY=false
PGHA_TLS_ONLY=false
PGHA_TLS_ENABLED=false
PGHA_DATABASE=newkrom
******************************
Patroni env vars:
******************************
PATRONI_POSTGRESQL_CONNECT_ADDRESS=10.42.1.111:5432
PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
PATRONI_NAME=newkrom-dbbff8789-2cqgf
PATRONI_SCOPE=newkrom
PATRONI_RESTAPI_LISTEN=0.0.0.0:8009
PATRONI_POSTGRESQL_DATA_DIR=/pgdata/newkrom
PATRONI_RESTAPI_CONNECT_ADDRESS=10.42.1.111:8009
PATRONI_LOG_LEVEL=INFO
PATRONI_KUBERNETES_LABELS={vendor: "crunchydata"}
PATRONI_KUBERNETES_SCOPE_LABEL=crunchy-pgha-scope
PATRONI_KUBERNETES_NAMESPACE=pgo
******************************
Patroni bootstrap method: initdb
******************************
Patroni configuration file:
******************************
bootstrap:
  method: initdb
  pgbackrest_init:
    command: '/opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh
      primary'
    keep_existing_recovery_conf: true
  existing_init:
    command: '/opt/crunchy/bin/postgres-ha/bootstrap/create-from-existing.sh'
    keep_existing_recovery_conf: true
  dcs:
    postgresql:
      parameters:
        jit: off
        unix_socket_directories: /tmp
        wal_level: logical
        archive_mode: on
        archive_command: 'source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh
          && pgbackrest archive-push "%p"'
      use_slots: false
      recovery_conf:
        restore_command: 'source /opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-set-env.sh
          && pgbackrest archive-get %f "%p"'
  post_bootstrap: /opt/crunchy/bin/postgres-ha/bootstrap/post-bootstrap.sh
postgresql:
  use_unix_socket: true
  pgpass: /tmp/.pgpass
  create_replica_methods:
  - pgbackrest
  - basebackup
  pgbackrest:
    command: '/opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh
      replica'
    keep_data: true
    no_params: true
  pgbackrest_standby:
    command: '/opt/crunchy/bin/postgres-ha/pgbackrest/pgbackrest-create-replica.sh
      standby'
    keep_data: true
    no_params: true
    no_master: 1
  remove_data_directory_on_rewind_failure: true
  callbacks:
    on_role_change: /opt/crunchy/bin/postgres-ha/callbacks/pgha-on-role-change.sh
  pg_hba:
  - local all postgres peer
  - host replication primaryuser 0.0.0.0/0 md5
  - host all primaryuser 0.0.0.0/0 reject
  - host all all 0.0.0.0/0 md5
Mon Aug 16 07:08:16 UTC 2021 INFO: Applying SSHD..
Mon Aug 16 07:08:16 UTC 2021 INFO: Checking for SSH Host Keys in /sshd..
Mon Aug 16 07:08:16 UTC 2021 INFO: Checking for authorized_keys in /sshd
Mon Aug 16 07:08:16 UTC 2021 INFO: Checking for sshd_config in /sshd
Mon Aug 16 07:08:16 UTC 2021 INFO: setting up .ssh directory
Mon Aug 16 07:08:16 UTC 2021 INFO: Starting SSHD..
Mon Aug 16 07:08:16 UTC 2021 INFO: Starting background process to monitor Patroni initization and restart the database if needed
Mon Aug 16 07:08:16 UTC 2021 INFO: Initializing cluster bootstrap with command: '/usr/local/bin/patroni /tmp/postgres-ha-bootstrap.yaml'
Mon Aug 16 07:08:16 UTC 2021 INFO: Running Patroni as PID 1
2021-08-16 07:08:17,172 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-08-16 07:08:17,177 INFO: Lock owner: None; I am newkrom-dbbff8789-2cqgf
2021-08-16 07:08:17,228 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /pgdata/newkrom ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
2021-08-16 07:08:17.372 UTC [139] FATAL:  could not write to file "pg_wal/xlogtemp.139": No space left on device
child process exited with exit code 1
initdb: removing contents of data directory "/pgdata/newkrom"
pg_ctl: database system initialization failed
2021-08-16 07:08:17,384 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-08-16 07:08:17,428 INFO: renaming data directory to /pgdata/newkrom_2021-08-16-07-08-17
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1452, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1346, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1242, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1235, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
running bootstrap script ...
```
I investigate more about why the disk full error appeared it turned that there are a lot of WAL files. I think it's something related to the storage class.
Is there a way to retrieve data from the PV directly?

**Comment by jkatz** [comment]
> Is there a way to retrieve data from the PV directly?

A lot of this depends on your underlying storage system. Some can be introspected directly, others can be used with something like `busybox` where you can mount the PVC to that and inspect it.
