### ISSUE TITLE
Migration pgo 4.x to 5.x no renaming of the primary user -> no replication without manual correction

### ISSUE THREAD

**Issue by Schmaetz** [CrunchyData/postgres-operator#3087]
Please ensure you do the following when reporting a bug:

## Overview

When migrating a database from pgo 4.x to 5.x, there is a problem with the replication user. In Major 4 it is called primaryuser and in Major 5 __crunchyrepl. This renaming or the creation of a new user does not take place in the described variants of migration via standby cluster. 
Creation via cluster definition is also not possible due to the underscore. 

## Environment

Please provide the following details:

- Platform: Openshift 4.9.22
- Platform Version: 5.0.4
- Postgres Version 13, 14

### REPRO

Provide steps to get to the error condition:

1. Create a Cluster on pgo 4.x 
2. Migrate the Cluster to pgo 5.x via Standby-Cluster
3. Promote Cluster to Primary
4. Checkout Roles on the Cluster 

### EXPECTED

I actually expect the operator to create the user or rename the primaryuser as soon as the cluster is promoted. Logically, it is not possible before that :)

### ACTUAL

After the cluster is promoted, the primary user remains and there is no __Crunchyrepl user, so replicas cannot start replication. The replica reports the following error:

2022-03-10 07:54:02,355 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 849, in get_replica_timeline
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 844, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "_crunchyrepl" does not exist

## Logs

2022-03-10 07:54:02,355 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 849, in get_replica_timeline
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 844, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 44, in get_connection_cursor
    conn = psycopg.connect(**kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "_crunchyrepl" does not exist

**Comment by andrewlecuyer** [comment]
@Schmaetz please see the following commit, which will be included in an upcoming release and provides documentation/instructions for dealing with this scenario:

https://github.com/CrunchyData/postgres-operator/commit/62a6d9341004b776b79271bcfd65a48b3bcf2889?short_path=d2c02e5#diff-d2c02e5242e06b07469e4c26f9e3af92d1b87df35cd8dc51e6af0cfad99c44e2

As you'll also see, we do plan to automate this in a future release.

**Comment by Schmaetz** [comment]
@andrewlecuyer 
Great, thanks for the information and the automated rollout of the user in the future :) 

Many greetings
