### ISSUE TITLE
Restored cluster in crashloop unable to bootstrap

### ISSUE THREAD

**Issue by trevor-primer** [CrunchyData/postgres-operator#3263]
## Overview
After starting up a new cluster with datasource of a backup in Azure blob container, the new cluster fails to bootstrap

## Environment
- AKS version 1.21.7
- ubi8-5.1.1-0
- Postgres 13
- Azure networked storage

### REPRO
- Create new cluster with datasource of an Azure blob container backup
- Restore pod completes
- New cluster pod starts up with bootstrap error

### EXPECTED
New cluster starts up with restored data

### ACTUAL
Cluster ends up in crashloop

## Logs
- Operator
```
time="2022-06-16T15:37:34Z" level=debug msg="reconciled instance" file="internal/controller/postgrescluster/instance.go:1129" func="postgrescluster.(*Reconciler).reconcileInstance" instance=config-service-restore-pgha1-8fnd name=config-service-restore namespace=config-service reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.1.1-0
time="2022-06-16T15:37:34Z" level=debug msg="reconciled instance" file="internal/controller/postgrescluster/instance.go:1129" func="postgrescluster.(*Reconciler).reconcileInstance" instance=config-service-restore-pgha1-64bf name=config-service-restore namespace=config-service reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.1.1-0
time="2022-06-16T15:37:34Z" level=debug msg="reconciled instance" file="internal/controller/postgrescluster/instance.go:1129" func="postgrescluster.(*Reconciler).reconcileInstance" instance=config-service-restore-pgha1-mdh9 name=config-service-restore namespace=config-service reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.1.1-0
time="2022-06-16T15:37:34Z" level=debug msg="reconciled instance set" file="internal/controller/postgrescluster/instance.go:1025" func="postgrescluster.(*Reconciler).scaleUpInstances" instance-set=pgha1 name=config-service-restore namespace=config-service reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.1.1-0
time="2022-06-16T15:37:35Z" level=debug msg="skipping SSH reconciliation, no repo hosts configured" file="internal/controller/postgrescluster/pgbackrest.go:1862" func="postgrescluster.(*Reconciler).reconcilePGBackRestConfig" name=config-service-restore namespace=config-service reconcileResource=repoConfig reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.1.1-0
time="2022-06-16T15:37:35Z" level=debug msg="reconciled cluster" file="internal/controller/postgrescluster/controller.go:313" func="postgrescluster.(*Reconciler).Reconcile" name=config-service-restore namespace=config-service reconciler group=postgres-operator.crunchydata.com reconciler kind=PostgresCluster version=5.1.1-0
```

- Restore pod 
```
WARN: unable to open log file '/pgdata/pgbackrest/log/db-restore.log': No such file or directory
      NOTE: process will continue without log file.
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/pgdata/pg13' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
2022-06-16 15:02:28.351 GMT [19] LOG:  starting PostgreSQL 13.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
2022-06-16 15:02:28.354 GMT [19] LOG:  listening on IPv6 address "::1", port 5432
2022-06-16 15:02:28.355 GMT [19] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2022-06-16 15:02:28.371 GMT [19] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-06-16 15:02:28.380 GMT [20] LOG:  database system was interrupted; last known up at 2022-06-16 14:43:26 GMT
2022-06-16 15:02:28.845 GMT [20] LOG:  starting archive recovery
2022-06-16 15:02:29.382 GMT [20] LOG:  restored log file "0000001E.history" from archive
2022-06-16 15:02:29.978 GMT [20] LOG:  restored log file "0000001E000000000000006F" from archive
2022-06-16 15:02:30.079 GMT [20] LOG:  redo starts at 0/6F000028
2022-06-16 15:02:30.674 GMT [20] LOG:  restored log file "0000001E0000000000000070" from archive
2022-06-16 15:02:30.776 GMT [20] LOG:  consistent recovery state reached at 0/70000050
2022-06-16 15:02:30.776 GMT [19] LOG:  database system is ready to accept read only connections
2022-06-16 15:02:32.038 GMT [20] LOG:  restored log file "0000001E0000000000000071" from archive
2022-06-16 15:02:32.669 GMT [20] LOG:  redo done at 0/71000148
2022-06-16 15:02:33.255 GMT [20] LOG:  restored log file "0000001E0000000000000071" from archive
2022-06-16 15:02:33.927 GMT [20] LOG:  selected new timeline ID: 31
2022-06-16 15:02:34.074 GMT [20] LOG:  archive recovery complete
2022-06-16 15:02:34.581 GMT [20] LOG:  restored log file "0000001E.history" from archive
2022-06-16 15:02:34.632 GMT [19] LOG:  database system is ready to accept connections
2022-06-16 15:02:34.639 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:34.639 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:35.654 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:35.654 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:36.614 GMT [19] LOG:  received fast shutdown request
2022-06-16 15:02:36.618 GMT [19] LOG:  aborting any active transactions
2022-06-16 15:02:36.622 GMT [19] LOG:  background worker "logical replication launcher" (PID 52) exited with exit code 1
2022-06-16 15:02:36.623 GMT [24] LOG:  shutting down
2022-06-16 15:02:36.658 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:36.658 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:36.658 GMT [51] WARNING:  archiving write-ahead log file "0000001F.history" failed too many times, will try again later
2022-06-16 15:02:36.719 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:36.719 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:36.768 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:36.768 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:37.795 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:37.795 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:37.796 GMT [51] WARNING:  archiving write-ahead log file "0000001F.history" failed too many times, will try again later
2022-06-16 15:02:37.806 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:37.806 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:38.814 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:38.814 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:39.819 GMT [51] LOG:  archive command failed with exit code 1
2022-06-16 15:02:39.819 GMT [51] DETAIL:  The failed archive command was: false
2022-06-16 15:02:39.819 GMT [51] WARNING:  archiving write-ahead log file "0000001F.history" failed too many times, will try again later
2022-06-16 15:02:39.822 GMT [19] LOG:  database system is shut down
```

- New cluster pod
```
2022-06-16 15:42:09,034 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-06-16 15:42:09,037 INFO: Lock owner: None; I am config-service-restore-pgha1-64bf-0
2022-06-16 15:42:09,098 INFO: trying to bootstrap a new cluster
2022-06-16 15:42:09,098 INFO: Running custom bootstrap script: mv "/pgdata/pg13_bootstrap" "/pgdata/pg13"
mv: cannot stat '/pgdata/pg13_bootstrap': No such file or directory
2022-06-16 15:42:09,103 INFO: removing initialize key after failed attempt to bootstrap the cluster
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/patroni/__main__.py", line 143, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/site-packages/patroni/__main__.py", line 135, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/site-packages/patroni/__main__.py", line 105, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/site-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/__main__.py", line 108, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1503, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1377, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1269, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1262, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
```

**Comment by trevor-primer** [comment]
I am using different cluster names unlike in https://github.com/CrunchyData/postgres-operator/issues/3058 , both clusters are in same namespace.

**Comment by David-Angel** [comment]
What is the solution to this?
I am seeing the same thing.

**Comment by bendilley** [comment]
I'm also having this problem. Did you manage to solve it @trevor-primer ?

**Comment by David-Angel** [comment]
The solution in my case was to 

1. Make sure "postgresql.conf" exists using this:  "touch /pgdata/data/postgresql.conf"
2. Set the ownership of all files in the data directory using this:   chown -R 26:26 /pgdata/data

And of course if using Kubernetes set the data source.
  dataSource:
    volumes:
      pgDataVolume:
        pvcName: {{ postgres_pvc }}
        directory: data

After that migration works perfectly.

**Comment by bendilley** [comment]
Thanks @David-Angel - I think I've got a different problem that looks nearly identical to the output in @trevor-primer's report. I might have the problem in #3058 as I'm reusing the cluster name in different namespaces, but I'm also using pgbackrest backups from non-PGO instances, so I might be too far off-piste to begin with 🤷🏻
