### ISSUE TITLE
pgo5 error after running for a while

### ISSUE THREAD

**Issue by nothinggift** [CrunchyData/postgres-operator#3299]
## Overview

The same error occurs every few days when pgo5 is running normally, the new database connection cannot be established, deleting the pod and rebuilding will fix it, and then the same error occurs again a few days later

## Environment

Please provide the following details:

- Platform: (`Kubernetes`)
- Platform Version: (`1.23.1`)
- PGO Image Tag: ( `ubi8-5.1.0-0` and `ubi8-5.0.5-0`)
- Postgres Version (`14` and `13`)

## Logs

The error below keeps repeating

2022-07-13 02:31:46,159 INFO: Lock owner: project-instance1-xqz2-0; I am project-instance1-nmwk-0
2022-07-13 02:31:46,301 ERROR: Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1503, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1467, in _run_cycle
    msg = self.process_healthy_cluster()
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 1059, in process_healthy_cluster
    self.state_handler.name, lock_owner), refresh=False)
  File "/usr/local/lib/python3.6/site-packages/patroni/ha.py", line 429, in follow
    change_required, restart_required = self.state_handler.config.check_recovery_conf(node_to_follow)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/config.py", line 698, in check_recovery_conf
    primary_conninfo = params['primary_conninfo']
KeyError: 'primary_conninfo'
2022-07-13 02:31:46,306 INFO: Unexpected exception raised, please report it as a BUG

**Comment by nothinggift** [comment]
big problem

Deleting the pod can indeed solve the error reporting problem, but the administrator account has lost administrator privileges, and now the database can no longer be created, and the configuration cannot be modified to create a new administrator, nor can the previous account be granted the administrator role, even the postgres account does not then the administrator

Because of this problem, I was forced to create a new cluster, now how do I create a new database?

**Comment by benjaminjb** [comment]
Hmmm, that's curious, but just to make sure I understand, you list two PGO image versions (`ubi8-5.1.0-0` and `ubi8-5.0.5-0`) and two PG version (`14` and `13`) -- was there any upgrading? Were these separate, clean installations of PGO?

(It is not clear to me that this is the root of your problem, but there is documentation specific to upgrading from PGO `5.0` to `5.1`: https://access.crunchydata.com/documentation/postgres-operator/v5/upgrade/kustomize/#upgrading-from-pgo-v5-0-x-to-v5-1-x )

**Comment by benjaminjb** [comment]
Have not heard back on this, so closing for now, but reopen if you are still running into this issue.
