### ISSUE TITLE
PostgreSQL Cluster cannot fetch local timeline and lsn from replication connection

### ISSUE THREAD

**Issue by chooboonhooi** [CrunchyData/postgres-operator#3331]
Hello,

I tried to setup TLS for my postgreSQL cluster on OpenShift container platform. However, I have received the problem that the cluster cannot fetch local timeline and lsn from replication connection.

```
2022-08-01 09:30:49,039 ERROR: Can not fetch local timeline and lsn from replication connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 821, in get_replica_timeline
    with self.get_replication_connection_cursor(**self.config.local_replication_address) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/__init__.py", line 816, in get_replication_connection_cursor
    with get_connection_cursor(**conn_kwargs) as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/connection.py", line 43, in get_connection_cursor
    conn = psycopg2.connect(**kwargs)
  File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
FATAL:  no pg_hba.conf entry for replication connection from host "127.0.0.1", user "primaryuser", SSL off
```

Below is the rules in my pg_hba_conf:
```
- local all postgres peer
  - host replication primaryuser 0.0.0.0/0 md5
  - host all primaryuser 0.0.0.0/0 reject
  - host all all 0.0.0.0/0 md5
  - hostssl replication primaryuser 0.0.0.0/0 md5
  - hostssl all primaryuser 0.0.0.0/0 reject
  - hostssl all all 0.0.0.0/0 md5
```

Any help would be much appreciated. Many thanks!

**Comment by benjaminjb** [comment]
Hello, sorry to hear you were experiencing this. Are you still experiencing this problem?

If you're still experiencing this problem, can you share information on your setup (Kubernetes version, PGO version, PG version)?
