### ISSUE TITLE
Postgres operator crash loop panic: invalid configuration

### ISSUE THREAD

**Issue by justinhippo** [CrunchyData/postgres-operator#3487]
## Overview

In Rancher RKE2 cluster, postgres-operator and postgres-operator-upgrade continually crash with the same message immediately after starting `panic: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable`
## Environment

Please provide the following details:

- Platform: `Rancher`
- Platform Version: `2.6.9`
- PGO Image Tag: `ubi8-5.2.1-0`
- Postgres Version `14`
- Storage: `longhorn`

### REPRO

1) Update configuration of existing PGO cluster and apply
2) postgres-operator pod stuck in CrashLoopBackoff

### EXPECTED

1. postgres-operator updates configuration

### ACTUAL

1. postgres-operator crashes

## Logs

```time="2022-12-08T00:10:52Z" level=debug msg="debug flag set to true" file="cmd/postgres-operator/main.go:68" func=main.main version=5.2.1-0
panic: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
goroutine 1 [running]:
main.assertNoError(...)
github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:41
main.main()
github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:73 +0x594
```
## Additional Information

Tried upgrading PGO cluster to latest version with no success, just caused `postgres-operator-upgrade` to start crashing as well

**Comment by justinhippo** [comment]
This ended up being that the two service accounts were created with a default of `automountServiceAccountToken: false` instead of `true`. Switching this value resolves the issue, but the CRD install may want to be updated to explicitly set the field
