### ISSUE TITLE
pgo pod keeps restarting

### ISSUE THREAD

**Issue by Eric-zch** [CrunchyData/postgres-operator#3635]
## Overview

I built docker image postgres-operator:ubi8-5.3.1-0 by referring [Dockerfile](https://github.com/CrunchyData/postgres-operator/blob/master/build/postgres-operator/Dockerfile) and installed it on my openshift environment. There is an error for pgo pod. As there is no Dockerfile for postgres-operator-upgrade,  I did not install postgres-operator-upgrade. It works for pgo 5.2.0, but does not work for pgo 5.3.1

## Environment
- Platform: OpenShift
- Platform Version: 4.10.55
- PGO Image Tag: ubi8-5.3.1-0

## Logs
```
oc get po
NAME                   READY   STATUS    RESTARTS      AGE
pgo-5f99dbcb9d-xdwxc   1/1     Running   2 (77s ago)   5m28s

oc logs -f pgo-5f99dbcb9d-xdwxc
time="2023-04-17T02:56:49Z" level=debug msg="debug flag set to true" version=5.3.1-0
time="2023-04-17T02:56:49Z" level=info msg="feature gates enabled" PGO_FEATURE_GATES= version=5.3.1-0
I0417 02:56:50.789148       1 request.go:601] Waited for 1.026149647s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/autoscaling.openshift.io/v1beta1?timeout=32s
time="2023-04-17T02:56:52Z" level=info msg="Metrics server is starting to listen" addr=":8080" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="detected OpenShift environment" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="upgrade checking enabled" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="starting controller runtime manager and will wait for signal to exit" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting server" addr="[::]:8080" kind=metrics path=/metrics version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1beta1.PostgresCluster" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.ConfigMap" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Endpoints" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.PersistentVolumeClaim" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Secret" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Service" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=pgupgrade controllerGroup=postgres-operator.crunchydata.com controllerKind=PGUpgrade source="kind source: *v1beta1.PGUpgrade" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.ServiceAccount" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=pgupgrade controllerGroup=postgres-operator.crunchydata.com controllerKind=PGUpgrade source="kind source: *v1.Job" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Deployment" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.StatefulSet" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=pgupgrade controllerGroup=postgres-operator.crunchydata.com controllerKind=PGUpgrade source="kind source: *v1beta1.PostgresCluster" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Job" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting Controller" controller=pgupgrade controllerGroup=postgres-operator.crunchydata.com controllerKind=PGUpgrade version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Role" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.RoleBinding" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.CronJob" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.PodDisruptionBudget" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Pod" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.StatefulSet" version=5.3.1-0
time="2023-04-17T02:56:52Z" level=info msg="Starting Controller" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster version=5.3.1-0
W0417 02:56:52.777709       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
E0417 02:56:52.777767       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
W0417 02:56:53.726434       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
E0417 02:56:53.726470       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
W0417 02:56:56.209359       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
E0417 02:56:56.209380       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
time="2023-04-17T02:57:00Z" level=debug msg="could not complete upgrade check" response="Get \"https://operator-maestro.crunchydata.com/pgo-versions\": x509: certificate signed by unknown authority" version=5.3.1-0
W0417 02:57:00.634102       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
E0417 02:57:00.634123       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
W0417 02:57:11.128521       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
E0417 02:57:11.128547       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
W0417 02:57:25.711285       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
E0417 02:57:25.711306       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
W0417 02:57:54.277025       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
E0417 02:57:54.277053       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
W0417 02:58:35.747208       1 reflector.go:324] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
E0417 02:58:35.747227       1 reflector.go:138] k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PGUpgrade: failed to list *v1beta1.PGUpgrade: pgupgrades.postgres-operator.crunchydata.com is forbidden: User "system:serviceaccount:crunchy-postgres-operator:pgo" cannot list resource "pgupgrades" in API group "postgres-operator.crunchydata.com" at the cluster scope
time="2023-04-17T02:58:52Z" level=error msg="Could not wait for Cache to sync" controller=pgupgrade controllerGroup=postgres-operator.crunchydata.com controllerKind=PGUpgrade error="failed to wait for pgupgrade caches to sync: timed out waiting for cache to be synced" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=error msg="Could not wait for Cache to sync" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster error="failed to wait for postgrescluster caches to sync: timed out waiting for cache to be synced" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=info msg="Stopping and waiting for non leader election runnables" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=error msg="failed to get informer from cache" error="Timeout: failed waiting for *v1beta1.PGUpgrade Informer to sync" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=info msg="Stopping and waiting for leader election runnables" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for postgrescluster caches to sync: timed out waiting for cache to be synced" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=error msg="error received after stop sequence was engaged" error="context canceled" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=info msg="Stopping and waiting for caches" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=info msg="Stopping and waiting for webhooks" version=5.3.1-0
time="2023-04-17T02:58:52Z" level=info msg="Wait completed, proceeding to shutdown the manager" version=5.3.1-0
panic: failed to wait for pgupgrade caches to sync: timed out waiting for cache to be synced

goroutine 1 [running]:
main.assertNoError(...)
	github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:44
main.main()
	github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:122 +0x4c0
```

**Comment by Eric-zch** [comment]
I do not have such an issue with pgo 5.2.0
```
✗ oc logs -f pgo-5584b6c656-2srlz
time="2023-04-17T03:25:57Z" level=debug msg="debug flag set to true" version=5.2.0-0
I0417 03:25:58.592619       1 request.go:601] Waited for 1.017235933s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/k8s.cni.cncf.io/v1?timeout=32s
time="2023-04-17T03:26:00Z" level=info msg="Metrics server is starting to listen" addr=":8080" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="detected OpenShift environment" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="starting controller runtime manager and will wait for signal to exit" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="upgrade checking enabled" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="detected OpenShift environment" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting server" addr="[::]:8080" kind=metrics path=/metrics version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1beta1.PostgresCluster" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.ConfigMap" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Endpoints" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.PersistentVolumeClaim" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Secret" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Service" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.ServiceAccount" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Deployment" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.StatefulSet" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Job" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Role" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.RoleBinding" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.CronJob" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.PodDisruptionBudget" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.Pod" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting EventSource" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster source="kind source: *v1.StatefulSet" version=5.2.0-0
time="2023-04-17T03:26:00Z" level=info msg="Starting Controller" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster version=5.2.0-0
time="2023-04-17T03:26:01Z" level=info msg="Starting workers" controller=postgrescluster controllerGroup=postgres-operator.crunchydata.com controllerKind=PostgresCluster version=5.2.0-0 worker count=2
time="2023-04-17T03:26:01Z" level=info msg="{\"pgo_versions\":[{\"tag\":\"v5.3.0\"},{\"tag\":\"v5.2.1\"},{\"tag\":\"v5.2.0\"},{\"tag\":\"v5.1.4\"},{\"tag\":\"v5.1.3\"},{\"tag\":\"v5.1.2\"},{\"tag\":\"v5.1.1\"},{\"tag\":\"v5.1.0\"},{\"tag\":\"v5.0.9\"},{\"tag\":\"v5.0.8\"},{\"tag\":\"v5.0.7\"},{\"tag\":\"v5.0.6\"},{\"tag\":\"v5.0.5\"},{\"tag\":\"v5.0.4\"},{\"tag\":\"v5.0.3\"},{\"tag\":\"v5.0.2\"},{\"tag\":\"v5.0.1\"},{\"tag\":\"v5.0.0\"}]}" X-Crunchy-Client-Metadata="{\"deployment_id\":\"34f06fea-877d-457d-bb8b-3e3dd49329c6\",\"kubernetes_env\":\"v1.23.12+a57ef08\",\"pgo_clusters_total\":0,\"pgo_version\":\"5.2.0-0\",\"is_open_shift\":true}" version=5.2.0-0
```
