### ISSUE TITLE
Postgres replica pod stuck in CrashLoopBackOff after worker node failure - postgres-startup init container failing

### ISSUE THREAD

**Issue by johnswarbrick-napier** [CrunchyData/postgres-operator#3716]
I have a three node PostgreSQL 13 cluster managed by PGO 5.3.2 running in Azure AKS on Kubernetes 1.25.11.

Everything was fine until the worker node hosting one of the replica nodes failed and went offline for several hours.

When the worker node came back, the PostgreSQL pod cannot start and is stuck in CrashLoopBackOff.

It seems to be failing on the `postgres-startup` init container, and the only log output is:

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)
Initializing ...
/usr/bin/coreutils: error while loading shared libraries: /lib64/libcap.so.2: file too short
/usr/bin/coreutils: error while loading shared libraries: /lib64/libcap.so.2: file too short
::postgres-operator: uid::
::postgres-operator: gid::
::postgres-operator: postgres path::/usr/pgsql-13/bin/postgres
::postgres-operator: postgres version::
Expected PostgreSQL version 13
```

I tried deleting the pod, re-initialising the replica, and even deleting the PVC but the pod is still refusing to rejoin the cluster.

Does anyone have any suggestions on how I can recover this failed replica so I have a three node cluster again?

**UPDATE:** It seems that PGO may have spun up a new pod, instead of recovering the original, and it's this new pod that cannot join the existing cluster.

These are the cluster members (pods) from before the worker node failure:

```
transactions-instance1-pjtd-0
transactions-instance1-cnvs-0
transactions-instance1-clbv-0
```

...and these are the three cluster members (pods) from after the worker node failure:

```
transactions-instance1-pjtd-0
transactions-instance1-cnvs-0
transactions-instance1-2vw5-0
```

The failed pod `transactions-instance1-clbv-0` has been removed and replaced by a new pod `transactions-instance1-2vw5-0`, but `transactions-instance1-2vw5-0` cannot startup. I guess there must be missing certs or config or something similar that prevents this new pod from being correctly inserted into the cluster, although `patronictl list` does show pod `transactions-instance1-2vw5-0`?

### Environment

Please provide the following details:

- PGO: 5.3.2
- Platform: Azure AKS
- Platform Version: Kubernetes v1.25.11
- PGO Image Tag: ubi8-5.3.2-0
- Postgres Version: ubi8-13.7-1
- Storage: disk.csi.azure.com

### Extra Information

Output of `patronictl list`:

![image](https://github.com/CrunchyData/postgres-operator/assets/105818625/eb076030-f59f-4bdf-a553-665ddf25a7a0)

Trying to re-init the failed replica with patroni results in this error:

```
bash-4.4$ patronictl reinit transactions-ha transactions-instance1-2vw5-0 --force

Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 11, in <module>
    sys.exit(ctl())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/patroni/ctl.py", line 613, in reinit
    r = request_patroni(member, 'post', 'reinitialize', body)
  File "/usr/local/lib/python3.6/site-packages/patroni/ctl.py", line 171, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.6/site-packages/patroni/request.py", line 55, in __call__
    url = urlunparse((scheme, netloc, endpoint, '', '', ''))
  File "/usr/lib64/python3.6/urllib/parse.py", line 477, in urlunparse
    _coerce_args(*components))
  File "/usr/lib64/python3.6/urllib/parse.py", line 121, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

Output of `describe pod` for the `postgres-startup` init container:

```
Init Containers:
  postgres-startup:
    Container ID:  containerd://cfd92047f8474a173563566cb055477dff4b94dbd1ddef425e0f0aaa11728a8d
    Image:         napier.azurecr.io/crunchydata_crunchy-postgres:ubi8-13.7-1
    Image ID:      napier.azurecr.io/crunchydata_crunchy-postgres@sha256:1c522cd05c665a715ca8fc047142c5340bbdd6a00d3cbd9eabe63b06560e22ea
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -ceu
      --
      declare -r expected_major_version="$1" pgwal_directory="$2" pgbrLog_directory="$3"
      permissions() { while [[ -n "$1" ]]; do set "${1%/*}" "$@"; done; shift; stat -Lc '%A %4u %4g %n' "$@"; }
      halt() { local rc=$?; >&2 echo "$@"; exit "${rc/#0/1}"; }
      results() { printf '::postgres-operator: %s::%s\n' "$@"; }
      recreate() (
        local tmp; tmp=$(mktemp -d -p "${1%/*}"); GLOBIGNORE='.:..'; set -x
        chmod "$2" "${tmp}"; mv "$1"/* "${tmp}"; rmdir "$1"; mv "${tmp}" "$1"
      )
      safelink() (
        local desired="$1" name="$2" current
        current=$(realpath "${name}")
        if [ "${current}" = "${desired}" ]; then return; fi
        set -x; mv --no-target-directory "${current}" "${desired}"
        ln --no-dereference --force --symbolic "${desired}" "${name}"
      )
      echo Initializing ...
      results 'uid' "$(id -u)" 'gid' "$(id -G)"
      results 'postgres path' "$(command -v postgres)"
      results 'postgres version' "${postgres_version:=$(postgres --version)}"
      [[ "${postgres_version}" =~ ") ${expected_major_version}"($|[^0-9]) ]] ||
      halt Expected PostgreSQL version "${expected_major_version}"
      results 'config directory' "${PGDATA:?}"
      postgres_data_directory=$([ -d "${PGDATA}" ] && postgres -C data_directory || echo "${PGDATA}")
      results 'data directory' "${postgres_data_directory}"
      [[ "${postgres_data_directory}" == "${PGDATA}" ]] ||
      halt Expected matching config and data directories
      bootstrap_dir="${postgres_data_directory}_bootstrap"
      [ -d "${bootstrap_dir}" ] && results 'bootstrap directory' "${bootstrap_dir}"
      [ -d "${bootstrap_dir}" ] && postgres_data_directory="${bootstrap_dir}"
      if [[ ! -e "${postgres_data_directory}" || -O "${postgres_data_directory}" ]]; then
      install --directory --mode=0700 "${postgres_data_directory}"
      elif [[ -w "${postgres_data_directory}" && -g "${postgres_data_directory}" ]]; then
      recreate "${postgres_data_directory}" '0700'
      else (halt Permissions!); fi ||
      halt "$(permissions "${postgres_data_directory}" ||:)"
      results 'pgBackRest log directory' "${pgbrLog_directory}"
      install --directory --mode=0775 "${pgbrLog_directory}" ||
      halt "$(permissions "${pgbrLog_directory}" ||:)"
      install -D --mode=0600 -t "/tmp/replication" "/pgconf/tls/replication"/{tls.crt,tls.key,ca.crt}
      [ -f "${postgres_data_directory}/PG_VERSION" ] || exit 0
      results 'data version' "${postgres_data_version:=$(< "${postgres_data_directory}/PG_VERSION")}"
      [[ "${postgres_data_version}" == "${expected_major_version}" ]] ||
      halt Expected PostgreSQL data version "${expected_major_version}"
      [[ ! -f "${postgres_data_directory}/postgresql.conf" ]] &&
      touch "${postgres_data_directory}/postgresql.conf"
      safelink "${pgwal_directory}" "${postgres_data_directory}/pg_wal"
      results 'wal directory' "$(realpath "${postgres_data_directory}/pg_wal")"
      rm -f "${postgres_data_directory}/recovery.signal"
      startup
      13
      /pgdata/pg13_wal
      /pgdata/pgbackrest/log
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 30 Aug 2023 20:15:13 +0100
      Finished:     Wed, 30 Aug 2023 20:15:13 +0100
    Ready:          False
    Restart Count:  14
    Environment:
      PGDATA:         /pgdata/pg13
      PGHOST:         /tmp/postgres
      PGPORT:         5432
      KRB5_CONFIG:    /etc/postgres/krb5.conf
      KRB5RCACHEDIR:  /tmp
    Mounts:
      /pgconf/tls from cert-volume (ro)
      /pgdata from postgres-data (rw)
      /tmp from tmp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lzs6l (ro)
```

Config map for the replica:

```
apiVersion: v1
data:
  patroni.yaml: |
    # Generated by postgres-operator. DO NOT EDIT.
    # Your changes will not be saved.
    kubernetes: {}
    postgresql:
      basebackup:
      - waldir=/pgdata/pg13_wal
      create_replica_methods:
      - pgbackrest
      - basebackup
      pgbackrest:
        command: '''bash'' ''-ceu'' ''--'' ''install --directory --mode=0700 "${PGDATA?}"
          && exec "$@"'' ''-'' ''pgbackrest'' ''restore'' ''--delta'' ''--stanza=db''
          ''--repo=1'' ''--link-map=pg_wal=/pgdata/pg13_wal'' ''--type=standby'''
        keep_data: true
        no_master: true
        no_params: true
      pgpass: /tmp/.pgpass
      use_unix_socket: true
    restapi: {}
    tags: {}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-30T18:27:33Z"
  labels:
    postgres-operator.crunchydata.com/cluster: transactions
    postgres-operator.crunchydata.com/instance: transactions-instance1-2vw5
    postgres-operator.crunchydata.com/instance-set: instance1
  name: transactions-instance1-2vw5-config
  namespace: aml
  ownerReferences:
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PostgresCluster
    name: transactions
    uid: bfe3b094-f607-4fd9-adce-c57d5a7d6cfc
  resourceVersion: "3814003"
  uid: 7fa8370b-7321-4eb4-ac03-bb56aa4c80cf
```

**Comment by ValClarkson** [comment]
Hi @johnswarbrick-napier 

Sorry to hear you are running into issues.  Would you be able to provide us with your spec as well as logs from PGO when the pod crashed as well as when a the new pod was spun up or tried to connect to the new replica?

**Comment by johnswarbrick-napier** [comment]
Hi @ValClarkson, I'm going to close this ticket.

Turned out the problem was with the underlying Kubernetes worker node. It had gotten into a state where it couldn't re-attach the PVCs correctly.

Re-imaging the node fixed the problem.
