### ISSUE TITLE
v1.5.1 postgres-operator deployment fails to schedule

### ISSUE THREAD

**Issue by rimusz** [CrunchyData/postgres-operator#44]
getting `No nodes are available that match all of the following predicates:: PodToleratesNodeTaints (1).` 
I do not see any tolerations set in the deployment.

**Comment by jmccormick2001** [comment]
this is a bug that I just pushed a fix to....if you taint all your nodes that will go away...kubectl taint nodes --all node-role.kubernetes.io/master-

that is clearly not acceptable for a lot of users, so the fix will no longer add the affinity fragment to the pod by default.

**Comment by jmccormick2001** [comment]
just pushed version 1.5.2 which should fix that bug.

**Comment by rimusz** [comment]
awesome, thanks

**Comment by rimusz** [comment]
1.5.2 fails:
```
time="2017-09-22T09:38:07Z" level=error msg="error loading templateopen /operator-conf/affinity.json: no such file or directory"
panic: open /operator-conf/affinity.json: no such file or directory

goroutine 1 [running]:
github.com/crunchydata/postgres-operator/operator/util.LoadTemplate(0x1630d24, 0x1c, 0xc420079d40)
	/home/jeffmc/odev/src/github.com/crunchydata/postgres-operator/operator/util/util.go:74 +0x430
github.com/crunchydata/postgres-operator/operator/cluster.init.3()
	/home/jeffmc/odev/src/github.com/crunchydata/postgres-operator/operator/cluster/cluster_strategy_1.go:68 +0xcf
github.com/crunchydata/postgres-operator/operator/cluster.init()
	/home/jeffmc/odev/src/github.com/crunchydata/postgres-operator/operator/cluster/upgrade_strategy_1.go:237 +0xd4
github.com/crunchydata/postgres-operator/operator/server.init()
	/home/jeffmc/odev/src/github.com/crunchydata/postgres-operator/operator/server/server.go:322 +0x61
main.init()
	/home/jeffmc/odev/src/github.com/crunchydata/postgres-operator/operator/postgres-operator.go:42 +0x58
```

**Comment by jmccormick2001** [comment]
hmmn, can you verify that you rebuilt the configmap which should contain affinity.json?

**Comment by rimusz** [comment]
sorry stupid me, did not pull the latest changes from git repo, sorry for the false alarm.

**Comment by rimusz** [comment]
closing as 1.5.2 fixed issue
